### ISSUE TITLE
kW vs. kWh

### ISSUE THREAD

**Issue by mikaaalt** [tnmendes/watt#1]
The consumption history measures energy consumption (kWh). However the app GUI shows the unit kW (== power) everywhere except at the bottom (selection between energy and time display). Instead ”kWh” should be used.

**Comment by tnmendes** [comment]
Sorry just answering now for some reason I didn't receive a notification.

So now regarding your question, I didn't add the "h" hour for a design question.  I tried to make a app with a very simple and minimalist design.
 I can try in the future release to see if it looks good with "h" in a size much smaller than "kW", but I'm not sure this will work out good visually, but I promise I will test :)

**Comment by tnmendes** [comment]
Hey @mikaaalt, 

I finally solved this on the version 2.3.0. Can you take a look to see if everything is right!?
Thanks
