### ISSUE TITLE
Cost not updating

### ISSUE THREAD

**Issue by melbeckman** [tnmendes/watt#101]
I’ve been running this for about three days, and cumulative cost  is not increasing despite a steady power consumption. It has been $0.94 for all three days, and my power billing rate is $0.32. See attached screen shots. 

![F8E6BCB8-5011-4FAD-B37B-D3EE8CD57785](https://user-images.githubusercontent.com/52871602/224915141-a7e5ee11-0c09-4d06-b6c5-881b8fc35e45.png)
![979C3B00-2DBC-4C55-A893-29D2959CD0BF](https://user-images.githubusercontent.com/52871602/224915154-5d61809f-03a5-41e1-859c-7148f66e43f1.png)

**Comment by tnmendes** [comment]
Thank you for the feedback, yes pay attention and if it happens again let me know.
I'm going to close this issue for now and if it happens again I'll open it again

**Comment by tnmendes** [comment]
hi @melbeckman is the Watt app working well for your EP25 devices?

**Comment by melbeckman** [comment]
Alas, no. The EP25 itself randomly turns off and has to be reset and re-paired to turn back on. So I switched to the Emporia Energy metered plugs, which comes with its own app. So I’m not using the Watt app at all now. You might want to check out this Emporia app, because it’s quite powerful.

 -mel

On Dec 29, 2023, at 3:21 PM, Tiago Mendes ***@***.***> wrote:

﻿

hi @melbeckman<https://github.com/melbeckman> is the Watt app working well for your EP25 devices?
