### ISSUE TITLE
Can't add new EP25 devices in Watt that are added to Kasa

### ISSUE THREAD

**Issue by melbeckman** [tnmendes/watt#102]
I added my initial four TP-Link EP25 devices to Watt all at once. Now I want to add a fifth unit, but after adding it to Kasa, when I click the + button to add a device, it only shows my four existing devices, not the new device.

**Comment by tnmendes** [comment]
Hey @melbeckman I am going to ask you again to completely close the Watt app and open it again and see if that fixed the issue.

With version 5.0 of Watt app I am just updating the full list of your devices for the first time that you open the app, so to force getting all the new devices you need to completely close the Watt. I am going have to changed that in the next version.

**Comment by melbeckman** [comment]
I tried that but no luck. Then I logged out and logged a
Back in within Watt and all five devices appeared! Alas, all the stats and my billing rate of $0.32 reset as well. Are stats and configuration not retained across logins?

 -mel

On Mar 16, 2023, at 5:17 AM, Tiago Mendes ***@***.***> wrote:

﻿

Hey @melbeckman<https://github.com/melbeckman> I am going to ask you again to completely close the Watt app and open it again and see if that fixed the issue.

With version 5.0 of Watt app I am just updating the full list of your devices for the first time that you open the app, so to force getting all the new devices you need to completely close the Watt. I am going have to changed that in the next version.

**Comment by tnmendes** [comment]
Good to know that logout fixed the issue.
Yes, when you logout I am deleting all the information regarding the user.

I am going to closed this issue since is fixed for now.
