### ISSUE TITLE
Energy consumption disappeared

### ISSUE THREAD

**Issue by tiagoefreitas** [tnmendes/watt#103]
I tried the app and it recorded some energy consumption of a tplink hs110, then I didn’t use it for a month or 2 and now it’s all empty. 
The device has been off since.
Why can’t I access past data?

**Comment by tnmendes** [comment]
Hello Tiago, I am not saving anything on my Watt app side, all information comes directly from TP-Link servers.
Daily data is only stored for 30 days on the TP-Link servers, only annual data is stored for longer.

Watt now lets you export CSV data but just what you see on the chart.

**Comment by tiagoefreitas** [comment]
Any idea why the annual data may have disappeared?
Why doesn't watt save a local copy of previous months before they get
deleted from tp-link? otherwise I need to export every month not to loose
it.

**Comment by tnmendes** [comment]
"Any idea why the annual data may have disappeared?" - Did you do a reset? For example to change the Wifi network you need to reset

"Why doesn't watt save a local copy of previous months" - Watt is just a side project of mine. There are many features that Watt has to be developed and improved, but I don't always have time available, I have a full-time job, I have a family and I have a personal life. 🤷

**Comment by tiagoefreitas** [comment]
That's fine, I may use GPT-4 to add that feature soon as I need it :)
If I add a PR can you then update the app in app store?
Issue is setting up the dev / testing environment takes time haha

**Comment by tnmendes** [comment]
Thank you for your interest in contributing, have you worked with Realm Database? Or what databases are you used to working within Swift?

**Comment by tiagoefreitas** [comment]
I have worked with several different databases and languages, but not with
Realm or Swift. However I find all languages and databases are very similar
I just used to take a few minutes to look at the documentation and best
practices before GPT-4 arrived.

You may not be aware of the capabilities of GPT-4. Even if I was not an
engineer with experience, with GPT-4 it is very easy to do anything, please
get familiar with it and realize the developer job will end soon as anyone
can develop anything now.

**Comment by tiagoefreitas** [comment]
GPT4 is another league.
you can tell it your app there are several websites that index your github
repo in a vector store and feed it to GPT:
https://www.gptduck.com/
https://www.mendable.ai/
https://www.kapa.ai/

in alternative since GPT-4 has a bigger context window you can just copy
paste the whole code (but I don’t have access to the 32K version yet only
8K)
Anyway I will use this as a test case when I have time and let you know how
long it takes to implement it.

**Comment by tnmendes** [comment]
Interesting that these tools already exist, they were quick.
I will close this issue for now.
