### ISSUE TITLE
Energy consumption Graph color

### ISSUE THREAD

**Issue by sqlwizard** [tnmendes/watt#105]
Would it be possible to have more contrast between the background colors and the letters in the power consumption graph? White characters on cyan is a little hard to see at night on a tiny iPhone screen.

**Comment by tnmendes** [comment]
![IMG_998F1A26BC67-1](https://user-images.githubusercontent.com/9822076/226910072-ad071965-8044-4010-93c5-f0dc1b7dc69c.jpeg)

Are you referring to this information that is in the red squares?

**Comment by sqlwizard** [comment]
Hi!

Wow! I’m so impressed you answered so quickly! Yes, exactly! Little more contrast. My eyes are just not what they used to be 😀

Carlos Osorio
303.809.2151

On Mar 22, 2023, at 6:51 AM, Tiago Mendes ***@***.***> wrote:

﻿

[IMG_998F1A26BC67-1]<https://user-images.githubusercontent.com/9822076/226910072-ad071965-8044-4010-93c5-f0dc1b7dc69c.jpeg>

Are you referring to this information that is in the red squares?

**Comment by tnmendes** [comment]
Hey 👋
Thank you for the suggestion, I will try to add some black contrast, around the letters to see if improve the readability!!

**Comment by tnmendes** [comment]
Hey, 

So the Chart framework that i am using won't let me add an outline to the characters. 
What I did was increase the font size from 9 to 11 and changed the font-weight from regular to SemiBold.
Do you think this will make it easier to read?

Here is a print screen:
![Simulator Screenshot - iPhone 14 Pro - 2023-04-05 at 20 27 12](https://user-images.githubusercontent.com/9822076/230184705-544160b1-13ba-4e34-a473-25cf6e96a6e0.png)

**Comment by sqlwizard** [comment]
Perfect! Much easier to read. Thank you so much

Carlos Osorio
303.809.2151

On Apr 5, 2023, at 3:23 PM, Tiago Mendes ***@***.***> wrote:

﻿

Hey,

So the Chart framework that i am using won't let me add an outline to the characters.
What I did was increase the font size from 9 to 11 and changed the font-weight from regular to SemiBold.
Do you think this will make it easier to read?

Here is a print screen:
[Simulator Screenshot - iPhone 14 Pro - 2023-04-05 at 20 27 12]<https://user-images.githubusercontent.com/9822076/230184705-544160b1-13ba-4e34-a473-25cf6e96a6e0.png>

**Comment by tnmendes** [comment]
The new version 5.0.1 is out with the bigger font-weight. I am going to close this issue.

**Comment by sqlwizard** [comment]
Thank you

Carlos Osorio
303.809.2151

On Apr 10, 2023, at 2:40 AM, Tiago Mendes ***@***.***> wrote:

﻿

The new version 5.0.1 is out with the bigger font-weight. I am going to close this issue.
