### ISSUE TITLE
Energy cost in Colorado now TOU

### ISSUE THREAD

**Issue by sqlwizard** [tnmendes/watt#106]
Hi,
The energy cost now in Colorado is not as simple as taking the $/kWh. We just moved to Time Of Use, which has 3 different rates per day and the rates vary from winter to summer months. I realize calculating this across the entire app is not an easy undertaking. Are there any plans in your roadmap to account for TOU rates across the day and year?

**Comment by tnmendes** [comment]
Hey, calculations in Colorado are really tricky 😬😬😬
At this moment there is still no way to calculate using the TP-Link sockets, the plugs do not record hour by hour, they only record the day's accumulated.
