### ISSUE TITLE
Canadian App Store

### ISSUE THREAD

**Issue by objjg** [tnmendes/watt#109]
I’m sure this was written with the US in mind but we use these in Canada also and I’d like to be able to use it too. Could it be put in the Canadian App Store please… pretty please.

**Comment by tnmendes** [comment]
Thank you for reaching out and bringing this to my attention. I apologize for any inconvenience caused. Currently, there is a dispute with the Apple App Store regarding my apps, including Watt for Smart Devices. As a result, all my apps have been temporarily removed from the App Store.

I am actively working on resolving the situation with the App Store Review Team, and I hope to have my apps available again as soon as possible.

**Comment by objjg** [comment]
Good luck, I look forward to using your app. M.G. Ferris356 Waddell RdErinsville, Ontario. K0K2A0Cell (613) 532-0875On May 16, 2023, at 1:33 PM, Tiago Mendes ***@***.***> wrote:﻿
Thank you for reaching out and bringing this to my attention. I apologize for any inconvenience caused. Currently, there is a dispute with the Apple App Store regarding my apps, including Watt for Smart Devices. As a result, all my apps have been temporarily removed from the App Store.
I am actively working on resolving the situation with the App Store Review Team, and I hope to have my apps available again as soon as possible.

**Comment by tnmendes** [comment]
The app is again available 😌

**Comment by objjg** [comment]
Got it, I bought you a candy bar so I can test it for a month. My first comment is I need more than 16 devices. I have 18 Kasa and 3 Tapo.Can it be increased?Okiy is OK or Okay in English. Other than that it looks real good so far. Thanks for doing this. M.G. Ferris356 Waddell RdErinsville, OntarioK0K2A0Cell (613) 532-0875On May 18, 2023, at 5:57 PM, Tiago Mendes ***@***.***> wrote:﻿
The app is again available 😌

**Comment by tnmendes** [comment]
Hey @objjg, thank you for the support!! 
I'm limiting it to 16 devices to encourage using more than one space and thus create more organization and also encourage users to become a patreon of the project :D
Thanks in the next update I will change it to "Okay"
