### ISSUE TITLE
watt-for-smart-devices app iOS in the UK

### ISSUE THREAD

**Issue by anchorman22** [tnmendes/watt#110]
Hello

Is the app available in the UK? If not, may I put in a request to make it available?

Thanks

Anchorman

**Comment by tnmendes** [comment]
Hey @anchorman22, currently, there is a dispute with the Apple App Store regarding my apps, including Watt for Smart Devices. As a result, all my apps have been temporarily removed from the App Store.

I am actively working on resolving the situation with the App Store Review Team, and I hope to have my apps available again as soon as possible.

**Comment by anchorman22** [comment]
Oh no! I hope it gets resolved quickly, with no determent to yourself.

**Comment by tnmendes** [comment]
The app is again available 😌
