### ISSUE TITLE
Unable to switch  devices on/off, Status unknown - while energy consumption is measured

### ISSUE THREAD

**Issue by Robi1021** [tnmendes/watt#114]
Since a few days I receive an error when I try to switch my P115 on or of.
It states „failed to toggle switch, the operating couldn’t be completed. - Watt_for_Smart_Devises.-RequestError error8“
This happens on all of my 5 P115 devices and it doesn’t show state information.
However, it still reports energy consumption.

With the TAPO App everything works fine.

![IMG_3759](https://github.com/tnmendes/watt/assets/92546958/ad14046b-3c64-4664-b897-3d0efb712e34)

**Comment by tnmendes** [comment]
Hi, I already made a Hotflix to solve this problem with the Tapo device toggle.
The app has been submitted to the Apple AppStore review team and now it can take between 12 hours to 48 hours to be available!
Sorry for the inconvenience

**Comment by Robi1021** [comment]
I can confirm,
After the hotfix it’s working again.
