### ISSUE TITLE
iOS Shortcut Bug - Switch Brightness

### ISSUE THREAD

**Issue by ricky2389** [tnmendes/watt#116]
Hello,

I would like to raise a new issue for shortcuts.

The switch brightness action no longer lists the device names, only Select Variable and Ask Each Time

![IMG_7114](https://github.com/tnmendes/watt/assets/18630744/422c03b2-5a67-42f7-9d42-a9f9c83e3263)
![IMG_7115](https://github.com/tnmendes/watt/assets/18630744/ce05177c-4f56-4f8a-a32d-4043d12402d2)

**Comment by tnmendes** [comment]
Hey @ricky2389 

Can you try to add shortcut directly from the Watt app? If you open the Watt app > select space > select bulb > press the siri button > Switch Brightness > Done

Can you try to do this and tell me if it worked?
