### ISSUE TITLE
Folder "x.csv" doesn't exist error

### ISSUE THREAD

**Issue by drsantor001** [tnmendes/watt#117]
hello,

I download my watt consumption data weekly by individual smart plug and since i've renamed some of myplugs I now can no longer export data for a single smart plug because each time i get an error that says "Sorry... The folder "*Plug Name*.csv" doesnt' exist."

For some reason I can download the whole home data but not the data for the individual plug. Help would be much appreciated!

**Comment by tnmendes** [comment]
Hey,

Lets see if i can help you, can you reboot your phone? 
After the reboot can you also change the folder that you are using to save the CSV file?

**Comment by drsantor001** [comment]
I do not have a folder where i save the file on my phone, i usually airdrop
it to my computer.

**Comment by tnmendes** [comment]
I tried to replicate and failed, I changed device names and then AirDroped to Mac and everything worked fine.
Is this issue still happing to you?

If you "Save to Files" (save to your iPhone) does it work?

**Comment by drsantor001** [comment]
Any time i click on the icon to download CSV the error immediately pops up
before i select a destination.

**Comment by tnmendes** [comment]
One question are you using iPhone? Ipad? or MacOS?

**Comment by drsantor001** [comment]
iPhone

**Comment by thetonyleone** [comment]
I have issues on an iPad, when I click to export cvs it crashes the app.

**Comment by tnmendes** [comment]
There is a new version of the Watt app (v.  5.1.7) can you try and tell me if fix the issue?
If it didn't fix this issue can we try a different approach? The approach is to delete the Watt app and installed again to check if this can fix the problem.

**Comment by thetonyleone** [comment]
Issue seems fixed with updated version.

Thanks,
Tony
________________________________

**Comment by drsantor001** [comment]
Hi Tiago,Thank for all your help. Unfortunately the update and the removal and redownload does not appear to have solved the problem. I’m not sure where it is looking for a folder and if I can do anything on my phone to troubleshoot.This is what pops up when I try to download just one devices usage chart, vs when I do it for the whole home it pops up with the iPhone “share” screen.Sent from my iPhoneOn Jul 17, 2023, at 11:29 AM, Tiago Mendes ***@***.***> wrote:﻿
There is a new version of the Watt app (v.  5.1.7) can you try and tell me if fix the issue?
If it didn't fix this issue can we try a different approach? The approach is to delete the Watt app and installed again to check if this can fix the problem.

**Comment by drsantor001** [comment]
Hi Tiago,

I resolved the issue, my device name included a "/" which appeared to be
the problem!

**Comment by tnmendes** [comment]
@drsantor001 thank you for reporting this to me, in the next version I will add protection to "sanitize" the device name
