### ISSUE TITLE
CVS export on iPad crashes app

### ISSUE THREAD

**Issue by thetonyleone** [tnmendes/watt#120]
Was testing cvs export on my iPhone and iPad. iPhone 14 pro has no issues and exports to iPhone without issue. 
When I try to export on iPad it crashes the app. Tried multiple times. Not a huge issue but wanted to add to bug list. App crashes even after reboot.  

<img width="660" alt="image" src="https://github.com/tnmendes/watt/assets/17532271/b64ed0dd-d7a0-4129-85be-44e17e3da55c">

**Comment by tnmendes** [comment]
The new Watt version 5.1.7 should fix the problem with iPad export.
Thank you for reporting this issue!!

**Comment by thetonyleone** [comment]
Thank you my issue is good to go.
