### ISSUE TITLE
Translation to French

### ISSUE THREAD

**Issue by Musyanon** [tnmendes/watt#121]
Hello,

I would like to participate in your project by offering to translate the interface into French.

Let me know if this interests you. I appreciate your app and I would like to share it with friends who don't quite understand English :)

Have a good day !

**Comment by tnmendes** [comment]
Hey @Musyanon 

Thank you so much for your kind offer to help translate our app's interface into French.

I must admit that, at the moment, I haven't implemented translation features in the app, and it's not ready for multilingual support. Doing this change can be a really time-consuming process, and right now I do not have available time for that.

I'll certainly keep your generous offer in mind for future updates, thank you!!
