### ISSUE TITLE
Device status shortcut update

### ISSUE THREAD

**Issue by Averagesam** [tnmendes/watt#125]
Would it be possible to show the Siri shortcut output for a device status with the wattage amount in text opposed to number?

this way a following trigger can be added such as turn off if 1kw or wait 900 seconds and repeat. 

Aim to reduce phantom load

**Comment by tnmendes** [comment]
Hey @Averagesam 

I'm a little lost, isn't it better to have the value in "number"?
You can make rules in the shortcut, example "x > 100"
With "text" it is more difficult to make rules

**Comment by Averagesam** [comment]
Hi @tnmendes 

You are correct in that it would be better, but the only outcomes I am getting are 1 or 0 (Yes/No).
Please see screenshots attached showing both text and number results from output.

Ultimately I want the shortcut to be power usage under Xw turn off device, but currently unable due to the 1 or 0 options

Thanks.
![IMG_9837](https://github.com/tnmendes/watt/assets/147254047/2f82a8d0-6b9b-49b3-8487-a2b6f869b91c)
![IMG_9838](https://github.c
![IMG_9836](https://github.com/tnmendes/watt/assets/147254047/c0bfec56-6e32-403c-b585-c245c4b5ca23)
om/tnmendes/watt/assets/147254047/a65354ea-039d-4d5f-af68-3047c13c80b3)

**Comment by tnmendes** [comment]
I thought the consumption was coming out in the response Output but apparently it's just a bool saying whether it's connected to off.

In order not to break the shortcuts that Watt users may already have configured, and because sometimes a socket may be connected but with a consumption of 0 Watt, I will create a new option just to know the instantaneous consumption.

Thank you for reporting this to me

**Comment by Averagesam** [comment]
Hi @tnmendes 

I think it will be a great addition as you can cut high energy appliances before they finish their cycle, washers/dryers etc as they move into the end phases.

Where will this update be announced once available?

Thanks

**Comment by tnmendes** [comment]
Hey @Averagesam 

I just sent a Watt update where you can now get instant energy consumption via shortcuts.

Can you test?

**Comment by tnmendes** [comment]
Mark as done
