### ISSUE TITLE
Watts has stopped being able to control my TP-Link HS100

### ISSUE THREAD

**Issue by DHKaplan** [tnmendes/watt#126]
I'm running the latest iOS 17.0.3 on an iPhone 11 Pro. I have been using shortcuts and Watt to control a TP-Link HS100 successfully for awhile now. Quite recently, although I can't connect it directly with the advent of version iOs 17, Watt seems to hang when I try to control my device. Also, I've been getting a technical error after asking Siri to turn off the item: 

**Sorry, something went wrong. Watt says, "Technical error: (The operation couldn't be completed.
(SiriAppExtension.RequestError error 12.)
Code: 12
Brand:Kasa"
You can continue in Watt.
Open Watt

Any thoughts?
![Watt](https://github.com/tnmendes/watt/assets/5953197/0cf786b1-ab65-4611-9f40-d2349e3068c7)**

**Comment by tnmendes** [comment]
Hey @DHKaplan so error 12 supposedly is "session Invalidated" and looking at the description of Alamofire is: 
"Session was explicitly invalidated, possibly with the Error produced by the underlying URLSession."
This error description from Alamofire is a bit abstract to me 😅 


My iPad is on iOS 17 and I tested running Apple shortcut and I was able to turn on and off an HS100 plug.

When you open the app Watt, is it possible to turn it on and off directly from the app?

**Comment by DHKaplan** [comment]
@tnmendes Thanks for getting back... no Watt doesn't control it directly any more either... just hangs.

**Comment by tnmendes** [comment]
@DHKaplan have you activated two-factor activation on your Kasa account?

Can you log out of the Watt app and log back in?

**Comment by DHKaplan** [comment]
No 2FA, and logging out and back in fixed it! Thanks!

**Comment by tnmendes** [comment]
I'm glad it worked, we won't know what the reason for the error was, but at least it's resolved.

I'm going to close this issue, if the problem happens again you can reopen this issue.
