### ISSUE TITLE
Swipe order doesn’t match home screen order

### ISSUE THREAD

**Issue by LeftcoastBBQ** [tnmendes/watt#128]
In iOS 17.0.3, after rooms are initially created, if you change the order of rooms by holding down on a room, selecting “Reorder position”, and dragging any room to a new position, swiping from the Home Screen doesn’t match the new order. 

More an inconvenience than anything else, but not an expected behavior. 

Great app!

**Comment by tnmendes** [comment]
Hey @LeftcoastBBQ thank you for the report I will try to fix the order of spaces not being correct when you swipe.

This is my plan for the next few weeks of development:
- Support of the new Kasa Matter plugs
- New shortcut with value live consumption return
- Add a new button in each space to generate a chart with all the devices from that space 
- Fix the order of the spaces when you swipe

**Comment by LeftcoastBBQ** [comment]
Appreciate it. Like I said, it’s more of an unexpected behavior than anything else. I’m happy with you prioritizing the new plugs, as I have a few KP125M Matter plugs that would benefit more than swiping. Keep up the great work and your app is definitely worth a cup of coffee each month. JohnOn Oct 21, 2023, at 8:10 AM, Tiago Mendes ***@***.***> wrote:﻿
Hey @LeftcoastBBQ thank you for the report I will try to fix the order of spaces not being correct when you swipe.
This is my plan for the next few weeks of development:

Support of the new Kasa Matter plugs
New shortcut with value live consumption return
Add a new button in each space to generate a chart with all the devices from that space
Fix the order of the spaces when you swipe

**Comment by tnmendes** [comment]
Hey @LeftcoastBBQ I'm just writing to let you know that the bug you reported is resolved in version 5.2.6
Thanks for the bug report!!

**Comment by LeftcoastBBQ** [comment]
Updated the app and it works like a charm!  Thanks for the work, this is a cool app and definitely worth the subscription. On Jan 24, 2024, at 4:45 AM, Tiago Mendes ***@***.***> wrote:﻿
Hey @LeftcoastBBQ I'm just writing to let you know that the bug you reported is resolved in version 5.2.6
Thanks for the bug report!!
