### ISSUE TITLE
Don’t see energy consumption data. 

### ISSUE THREAD

**Issue by bejana** [tnmendes/watt#13]
I’m new to Kasa components, and purchased one specifically to see energy consumption. I have one that I set up that I can control, but I do not see any energy data. It all remains at zero. Does anyone know why?

I see a subscription service. Must in have a subscription to see energy consumption?

**Comment by tnmendes** [comment]
Hi @bejana,

What Kasa Smart devices that you bought? 
Just the Kasa Smart HS110, HS300 has the ability for Energy Monitoring, if you bought any other kasa smart device you not going to have that.
