### ISSUE TITLE
Tapo and Kasa Devices

### ISSUE THREAD

**Issue by Pratik72835** [tnmendes/watt#130]
Hello, how can I use the WATT app with multiple devices on Tapo and Kasa together in one place? 

I have logged in with my Kasa login details, and my Kasa devices can be seen. However, the WATT does not allow me to log into Tapo at the same time to bring in my Tapo devices. Can anyone help? 

I basically want to use the WATT app for all my smart devices from Tapo and Kasa.

**Comment by tnmendes** [comment]
Hey @Pratik72835 ,
Are you using the same email for Kasa and Tapo app? 
Watt only works with both brands when using the same email.
