### ISSUE TITLE
EP25 seen but no watt data

### ISSUE THREAD

**Issue by tuxon64** [tnmendes/watt#131]
I just bought the Kasa EP25, just for energy monitoring.  I can see my devices but zero usage data is being shown.  Shows up fine on the Kasa app.

**Comment by tnmendes** [comment]
Hi @tuxon64,
In the past, were you able to see consumption on that device in the Watt app? Do you know if there has been any firmware update in the last few weeks for that device? Do you have more than one EP25, if yes, it's happening to all devices?
Can you share a print screen from the same device as the chart screen in the Watt app and the consumer screen in the Kasa app? 

Thank you!!

**Comment by tuxon64** [comment]
Are you using the Python-Kasa library to write the code?  If so the EP25 aren’t supported.  I have a Kasa KP115 arriving later this week and will try with that.

**Comment by tnmendes** [comment]
I did everything from scratch in Swift, using Kasa and Tapo's own server communication as a basis.
I can see that 9 months ago other user also had the same issue with the EP25 and the chart 

https://github.com/tnmendes/watt/issues/101

**Comment by tuxon64** [comment]
So the KP115 does work with your Watt app.  I can also get the data from Terminal and a python script.  I’d like to write a small program to have the main data in the menubar.  I wrote a swift program years ago for my weather station but that looks like greek to me now.  Looks like I might need to scrap the 25’s for the 115.  Also within the Kasa app the data/charts are different for the two models.

**Comment by theogravity** [comment]
I also just got the EP25 plug and I see it in both my Kasa and Apple Home app, but Watt doesn't see it at all (as in it doesn't know it exists) when I try to add a new device to a group.

**Comment by tnmendes** [comment]
I'm going to try to prioritize trying to find out what's going on with EP25, probably Kasa is using some new API or way of obtaining the information for that device.

**Comment by tnmendes** [comment]
I'm testing here with EP25 and I'm able to add it to Watt and get values on the chart.
The EP25 that I am using is this version:
Hardware version": "1.0",
Firmware Version: "1.0.13 Build 231108 Rel.162846"

Do you guys have different versions??

**Comment by tuxon64** [comment]
My hardware version is 2.6 and firmware is 1.02 Build 231108 Release 163012.

I bought the four pack from Amazon a couple weeks ago.  I did read in the comments that someone bought the 2-pack and their screens/charts were different with the Kasa app.  I’ll have to check if there is a way to rollback the firmware.

**Comment by tnmendes** [comment]
I think that version is using a new API,  can you add one of your EP25 to one of my Kasa accounts for testing? 
If you can please send me an email "hi" mail to voless.app@gmail.com  and I will share with you the kasa account.

**Comment by tnmendes** [comment]
The Watt version 5.2.5 does now support Kasa EP25.
Special thanks to @tuxon64 for helping with the investigation :D
