### ISSUE TITLE
Past Years Disappeared 

### ISSUE THREAD

**Issue by BostonDani** [tnmendes/watt#132]
I was previously able to see my historical data from 2022. I just checked and it’s disappeared. Is there a limit on how long data is stored?

**Comment by tnmendes** [comment]
Hey @BostonDani ,

I wasn't aware that this was happening, but I can also replicate this issue. hmmmm Interesting.

So I'm using TP-Link servers to obtain consumption but apparently, they are now not allowing this access or they have deleted all consumption from the server in 2022. 


Technical answer:
I am requesting this to TP-Link servers:
`{
  "method": "passthrough",
  "params": {
    "deviceId": "xx_private_devices_id",
    "requestData": "{\"emeter\":{\"get_monthstat\":{\"year\":2022}}, \"schedule\":{\"get_monthstat\":{\"year\":2022}}}"
  }
}`

And this is the response from TP-Link servers.
`{
  "error_code": 0,
  "result": {
    "responseData": "{\"emeter\":{\"get_monthstat\":{\"month_list\":[],\"err_code\":0}},\"schedule\":{\"get_monthstat\":{\"month_list\":[],\"err_code\":0}}}"
  }
}`

In this device, the response should not be an empty array -> []
