### ISSUE TITLE
Device name incorrect in iOS Shortcuts

### ISSUE THREAD

**Issue by sawoodpearce** [tnmendes/watt#135]
I absolutely love Watt and iOS Shortcuts integration (thank you), though have observed a minor bug.

I have renamed a device in Kasa. The new device name appears correctly in Watt, but the old name appears in the device selection dropdown of Shortcuts.

If I use Watt to create one of the three preset Siri Shortcuts, the device name is then correct in Shortcuts.

See screenshots where Watt shows the correct names and Shortcuts shows an old name which is no longer in use. (The Shortcut was created weeks after the rename):

![IMG_2724](https://github.com/tnmendes/watt/assets/97291912/b142c409-466c-42aa-ad50-0b5125e354ce)
![IMG_2722](https://github.com/tnmendes/watt/assets/97291912/dce49127-da0f-478b-8a7e-cf1033754de2)

**Comment by tnmendes** [comment]
Hi, @sawoodpearce thank you for reporting this, I am able to replicate this bug.
I am marking this as a bug

**Comment by tnmendes** [comment]
This was fixed in the last version 5.2.11. 
I am going to mark this as done!
