### ISSUE TITLE
KP125M - waiting for the device loading 

### ISSUE THREAD

**Issue by dilansmead** [tnmendes/watt#136]
Can’t view the KP125M details to see the led, energy usage, etc.

**Comment by tnmendes** [comment]
Hi @dilansmead supposedly the KP125M is supported, the KP125M is using a new API. 
Could you share a print screen with the errors so I can try to understand?

By the way do you just have one KP125M? Or do you have more? Do you have different devices?

**Comment by dilansmead** [comment]
This is where it stops.Sent from my iPhoneOn Jan 15, 2024, at 1:51 PM, Tiago Mendes ***@***.***> wrote:﻿
Hi @dilansmead supposedly the KP125M is supported, the KP125M is using a new API.
Could you share a print screen with the errors so I can try to understand?
By the way do you just have one KP125M? Or do you have more? Do you have different devices?

**Comment by tnmendes** [comment]
Hey @dilansmead If you do a replay via email, I won't be able to see the print screen :-/ 
You have to open github and respond here.

**Comment by dilansmead** [comment]
![IMG_5826](https://github.com/tnmendes/watt/assets/66584563/c088fd08-bae7-46ca-b827-790242dda4f4)
This is where it stops on my app.

**Comment by tnmendes** [comment]
and it never finishes loading?

Have a look to my print screen, how many devices are lacking loading? Do you have the latest version of watt?
![413289743_1602494197156583_7082716679471696247_n](https://github.com/tnmendes/watt/assets/9822076/c55b2520-436d-46cd-a43e-c9f1cbd04ab1)

**Comment by tnmendes** [comment]
@dilansmead i did an upgrade (version 5.2.8 build 122) related to devices KP125M, can you check?
