### ISSUE TITLE
Energy Usage

### ISSUE THREAD

**Issue by speedstercamaro** [tnmendes/watt#137]
The live energy consumption loads but no historical data loads. 
![IMG_1616](https://github.com/tnmendes/watt/assets/50690539/53519dc4-f3e5-4271-a61c-b5e537c8dc27)

**Comment by tnmendes** [comment]
Hi David, are you still having the issue?
What devices are you using? (model)

**Comment by speedstercamaro** [comment]
Hello,

Yes I am using TP Link Kasa KP125M smart plugs

**Comment by Oryxski** [comment]
I am having the same issue. Any help much appreciated. Thx

**Comment by tnmendes** [comment]
Hey I have good news, I've found the reason for the problem of statistics not appearing on some devices.
I've now sent a new update to the AppStore which should be available in about 48 hours (v. 5.2.8 build 122).

Technical reason: i am requesting TP-Link servers for the device consumption for the last 2 months but on some devices they are ignoring my request dates and sending consumption for the last 3 months

**Comment by tnmendes** [comment]
The app is already available can you guys @speedstercamaro @Oryxski check if now everything is good?

**Comment by speedstercamaro** [comment]
Thank you for the updates, I can now see historical usage data

**Comment by Oryxski** [comment]
It appears to be working! Thanks!
