### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by derfeznoj** [tnmendes/watt#138]
It would be nice if there is access to devices via macosx widgets. I didn't see this in the UI, but maybe I'm missing something.

**Comment by tnmendes** [comment]
A few months ago I did some experiments but at the time I was having some difficulties implementing them. So I ended up pausing widget development.
I have to give it a second chance again 😄

**Comment by tnmendes** [comment]
So right now Watt does not have widgets just support for MacOS Shortcuts

**Comment by derfeznoj** [comment]
Tiago,

Thanks very much for the feedback. I’m looking for something quick and easy to turn some equipment on/off without going through multiple steps. I installed TP-Link to allow the Kasa device to appear via. HomeKit, but TP-Link has to be running to act as a bridge. 

I’ll look at a shortcut and see if that will work for my needs,

Regards,

Jim

**Comment by derfeznoj** [comment]
Tiago,

No need to create widgets for Watt! Based upon your excellent feedback that Watt can be scripted using a shortcut I created this:
￼

Then I added a Shortcut widget to the desktop:
￼

And, viola, it works very well!

Thanks for your help, this is just what I need.

Regards,

Jim

**Comment by tnmendes** [comment]
Great to hear that!! 😄 
I am going to close this issue!!
