### ISSUE TITLE
No historic power consumption data from KP125M

### ISSUE THREAD

**Issue by slads11** [tnmendes/watt#142]
I see its on your supported list and it does connect  but...
While it shows current power consumption there is no historic data hence empty graphs. I have attached screenshots showing this. Cheers
Simon Lucas

![IMG_7501](https://github.com/user-attachments/assets/ca83f5b5-f48c-420b-b36d-841810f34e51)
![IMG_0023](https://github.com/user-attachments/assets/865904a6-fc7e-483b-9984-537a40cd705a)
![IMG_0022 2](https://github.com/user-attachments/assets/93fc337a-b391-4e76-af1c-069b21b19b04)
![IMG_0024](https://github.com/user-attachments/assets/b98203f5-725c-4289-af06-a1d03909eaba)
![IMG_0026](https://github.com/user-attachments/assets/3ee311be-ef6a-4a1c-a57f-94e47bd5bf96)

**Comment by tnmendes** [comment]
Hey Simon, thanks for the warning, I have to investigate the reason for the problem

**Comment by tnmendes** [comment]
Hey @slads11 what is the Firmware Version of your KP125M? 
Is newer or older than 1.2.3 Build 240624?

**Comment by slads11** [comment]
Firmware Version
1.2.3 Build 240624 Rel.154806
Hardware Version
1.0Sent from my iPadOn Aug 13, 2024, at 14:23, Tiago Mendes ***@***.***> wrote:﻿
Hey @slads11 what is the Firmware Version of your KP125M?
Is newer or older than 1.2.3 Build 240624?

**Comment by tnmendes** [comment]
On versoo 5.2.10 of watt I did some fixes related to KP125M devices but still, I judge that will solve.
Did you buy the device at 60+ days? Is working now?
This is just a theory that I still haven't managed to confirm, I think this problem happens when the device is less than 60 days and I am making a request for the last 60 days' consumption results.

KP125M is a Kasa brand device but they are not using Kasa API but the API of Tapo, but it doesn't always have the same behavior as a Tapo :-/

**Comment by slads11** [comment]
Thanks for following up.. look like it is downloading ok now. I have about a month of data now. Sent from my iPadOn Sep 13, 2024, at 00:15, Tiago Mendes ***@***.***> wrote:﻿
On versoo 5.2.10 of watt I did some fixes related to KP125M devices but still, I judge that will solve.
Did you buy the device at 60+ days? Is working now?
This is just a theory that I still haven't managed to confirm, I think this problem happens when the device is less than 60 days and I am making a request for the last 60 days' consumption results.
KP125M is a Kasa brand device but they are not using Kasa API but the API of Tapo, but it doesn't always have the same behavior as a Tapo :-/
