### ISSUE TITLE
Overall live usage before 1pm pdt

### ISSUE THREAD

**Issue by speedstercamaro** [tnmendes/watt#143]
On the home screen and on each room overview the total live usage does not show in the morning before 1pm. In the afternoon I can open the app and the values appear. 

![image](https://github.com/user-attachments/assets/5e1b7fbe-17b3-4dd7-89f3-315bfacba26a)

**Comment by tnmendes** [comment]
Hey @speedstercamaro that is strange, from the image I can see that the loading 6...6, when it is 6 out of 6 he should update this label. 

What devices do you have? 
By the way, what time zone are you in? (assumed that it could be a problem related to timezone)

**Comment by speedstercamaro** [comment]
Hello,All of the devices are KP125M plugs. I am in the US Pacific Time zone. It could be timezone, in the morning it will continue to say loading. But after 1pm US Pacific it will display the total wattageThanksDavidOn Sep 3, 2024, at 3:52 AM, Tiago Mendes ***@***.***> wrote:﻿
Hey @speedstercamaro that is strange, from the image I can see that the loading 6...6, when it is 6 out of 6 he should update this label.
What devices do you have?
By the way, what time zone are you in? (assumed that it could be a problem related to timezone)

**Comment by speedstercamaro** [comment]
I have now been using it at version times of the day and data is loading and displaying correctly now

**Comment by tnmendes** [comment]
Thank you for updating, on my side, I didn't have time to do anything to try to solve this problem.
So perhaps some correction on the part of TP-Link side.

I am going to close this issue, If this problem appears again, we can reopen this issue.
