### ISSUE TITLE
Kasa Power Strip Naming

### ISSUE THREAD

**Issue by Mousikos2** [tnmendes/watt#144]
On power strips like the HS300, The Watt app brings over the serial ID of the power strip instead of each items name. Once you’ve added one of the strips or plugs you can hold and see the various names, but you cannot see them individually within the app or space.

Is there a way to name the power strip instead of pulling over the serial number, and is there a way to see each outlet separately on a multi outlet strip?

![IMG_5236](https://github.com/user-attachments/assets/1df517fd-c950-4888-a355-4fcc5d3e027b)

![IMG_5237](https://github.com/user-attachments/assets/7626b7d0-52a5-41fc-a288-d8ea57011923)

**Comment by tnmendes** [comment]
Hey @Mousikos2 

What the Watt app is doing is getting the name of the devices they have in the Kasa app, but for HS300 the Kasa app uses each plug as an independent device, but in the Watt app they are grouped together, that is why of that technical name.
At this point, what you can do to differentiate each HS300 is to use the "Custom Icon" and use an icon that is more specific.
To change the icon you have to select a plug, click in the top left corner, scroll down, and select "Custom Icon"

![IMG_3122](https://github.com/user-attachments/assets/11f4118a-1094-4571-acc6-e61bb8aef167)


![IMG_3123](https://github.com/user-attachments/assets/c1ea33a2-6672-4311-8b9d-98849a0adea1)
