### ISSUE TITLE
iOS 18 shortcut not working

### ISSUE THREAD

**Issue by thmskphoto** [tnmendes/watt#145]
“An error occurred while communicating with the app.”

It says this when I want to turn a device off or on.

This has been the case since the new version was updated and I use the Tapo tool.

![IMG_0354](https://github.com/user-attachments/assets/dce93e7b-9c93-42a8-8fd7-b365839d4f75)

**Comment by tnmendes** [comment]
Hey @thmskphoto did the same shortcut work before on iOS 17?
In the update I made this week on the app Watt I changed so that now Watt gets the last nickname from the device if you change the name. Can that be the problem?

**Comment by thmskphoto** [comment]
Hi @tnmendes!

I don't know what the problem could be, I haven't changed anything since the previous ios beta, it was also on my phone and every command worked perfectly there too since the update I can control a Tapo device via commands.

I already deleted the app and reinstalled it, I was happy with the commands and created a new one, I also restarted the phone but it doesn't work at all through commands. 

I have no problem with the application, it works, but the commands don't.

There must be a problem with the application because none of the commands work since the application was updated.

![IMG_0378](https://github.com/user-attachments/assets/739273b7-a0f7-4b4b-ac15-430646968731)

**Comment by Japmeet** [comment]
I have the exact same issue. Watt automations and shortcuts have stopped working. I have apps auto updating so I’d imagine it has to do with the watt update as well. 
if I switch to Kasa shortcuts, they work just fine. Tried reinstalling Watt and Kasa, logging out and back in. Restarted the phone, but nothing really worked.

**Comment by tnmendes** [comment]
I just made a Hotfix (right now is waiting for the Apple review team), in the previous update I made some changes related to the internal version management system.
It should now take between 4 and 48 hours for the update to become available on the App Store

**Comment by thmskphoto** [comment]
Thank You @tnmendes for quick hotfix!

I'll test it, I'll definitely write if it works!

**Comment by thmskphoto** [comment]
Hi @tnmendes!

After the update, everything works fine! Thanks for the quick fix!

**Comment by thmskphoto** [comment]
Hi @tnmendes!

After the update, everything works fine! Thanks for the quick fix!

**Comment by tnmendes** [comment]
Awesome thank you for testing!!!
