### ISSUE TITLE
Crash on opening

### ISSUE THREAD

**Issue by FrB-Tech** [tnmendes/watt#146]
Crash report attached
[Watt crash report.pdf](https://github.com/user-attachments/files/17379509/Watt.crash.report.pdf)

**Comment by FrB-Tech** [comment]
IOS 18.0.1

**Comment by tnmendes** [comment]
Hey, thanks for the report. One question is iOS or macOS?

Whenever you open the Watt app, is it crashing, like everytime? If you delete Watt and download it again and install it, does that solve the problem?

**Comment by FrB-Tech** [comment]
Sorry : yes it is Mac OS And after removed it is the dame as showed in attached report (new one from this morning)Yes the crash is on each launch  De : Tiago Mendes ***@***.***>Date : mardi, 15 octobre 2024 à 23:23À : tnmendes/watt ***@***.***>Cc : FrB-Tech ***@***.***>, Author ***@***.***>Objet : Re: [tnmendes/watt] Crash on opening (Issue #146)Hey, thanks for the report. One question is iOS or macOS?Whenever you open the Watt app, is it crashing, like everytime? If you delete Watt and download it again and install it, does that solve the problem?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by tnmendes** [comment]
I am not able to replicate on my machine that is also on macOS version 15.0.1 like you.
 i am going to try to update the Firebase version, I've been reading about some issues with the new Xcode and some Firebase version and it could be the source of the problem

**Comment by tnmendes** [comment]
Hey @FrB-Tech can you update the Watt for MacOS version to 5.2.14 and check that did fix your issue?

**Comment by tnmendes** [comment]
There is a new version for MacOS and for iOS, that I believe fixed this issue. 
I am going to close this thread, if you still have the issue we can open it again.
