### ISSUE TITLE
Siri Shortcuts in iOS14

### ISSUE THREAD

**Issue by plyonsii** [tnmendes/watt#15]
I just installed the app yesterday, I am able to run Siri shortcuts by pressing the buttons in shortcuts but when I ask Siri via voice it's unable to run the shortcuts. I also noticed there's a comment saying that Siri shortcuts is limited to iOS 13. Is there a non-bug or is the app not optimize for iOS 14? Not sure why it's not working￼ via voice commands

**Comment by tnmendes** [comment]
@plyonsii my iphone is one iOS 14 and is working I removed the app and reinstalled it and it's working.
What I notice on the iOS 14 it's more complicated to say voice commands. Can you try to change the Siri commands to other's voices commands just to check out.

Regarding that comment "is limited to iOS 13" that message should only appear if you were using iOS below 13, can you take a print screen of that message?

**Comment by plyonsii** [comment]
> @plyonsii my iphone is one iOS 14 and is working I removed the app and reinstalled it and it's working.
> 
> What I notice on the iOS 14 it's more complicated to say voice commands. Can you try to change the Siri commands to other's voices commands just to check out.
> 
> 
> 
> Regarding that comment "is limited to iOS 13" that message should only appear if you were using iOS below 13, can you take a print screen of that message? 

![image](https://user-images.githubusercontent.com/71850438/94203309-03b3d500-fe74-11ea-915b-b31f8dfc9275.jpeg)

**Comment by tnmendes** [comment]
oh that message, at the time I wrote that message there was still no iOS 14 and only left this message for historical context.

**Comment by plyonsii** [comment]
Your suggestion for correcting my Siri issue worked! I uninstalled the app and then reinstalled it and now my Siri shortcuts work! Thank you! I am loving the app and it hasn't even been 24 hours! :-)￼

**Comment by tnmendes** [comment]
Happy to hear that!!! :D
