### ISSUE TITLE
Cannot update energy cost

### ISSUE THREAD

**Issue by diffwin75** [tnmendes/watt#16]
The number pad hides the 'save' button. Perhsps if it was at a higher position on the page?

**Comment by tnmendes** [comment]
Hey @diffwin75, after you change the energy cost you can press anywhere on that screen that the number pad will be dismissed. If you have any problems let me know!!!

**Comment by tnmendes** [comment]
By the way in what country are you in? Is the pre-defined value on the app too far from the amount you are paying per kWh + tax? Thanks

**Comment by diffwin75** [comment]
Thanks, I finally figured that one out, but it would be simpler and easier if the button either moved when the number pad came up, or was already higher on the page, which many apps do, because that would avoid the situation.
 :)


Denver Latham Service Professional
661-343-4432

**Comment by tnmendes** [comment]
I'm glad you did it. I'll put it on my to-do list to change that screen.

@diffwin75 the rate of 0.148 USD is it too different from what you have?

**Comment by diffwin75** [comment]
Ours is running about .178 right now. I changed it more for better accuracy than anything. It wasn’t too far off, but I was just being specific (I can be a perfectionist).
:)


Denver Latham Service Professional
661-343-4432
