### ISSUE TITLE
Consumption data gone

### ISSUE THREAD

**Issue by FlorianAlexander** [tnmendes/watt#17]
I’m using a HS110 since January 2020. Now I just discovered that the data and statistics for January until May are gone. June onwards is still shown in the app. 

Is there a way how to recover the data or export and save it in the future?

**Comment by tnmendes** [comment]
Hi @FlorianAlexander, the Kasa devices store data daily information for +/- 30 days, and then monthly information is expected to be stored indefinitely.
Sometimes it happens that devices lose information and I think that was your case.

You have the roadmap here
https://watt-app.com/#app-brief2

I intend to add the functionality "Export the data to Excel (csv)"

I am currently working on version 2.5 which will improve the way of controlling all devices. Maybe in version 2.6 I can add the option to export
