### ISSUE TITLE
Minor UI issues (display units)

### ISSUE THREAD

**Issue by Olghn** [tnmendes/watt#18]
Two very minor observations when using a Kasa HS110 Smartplug

1. The real-time power monitoring has "Wh" appended. I believe it should just be "W". A measurement in Watts.
2. The electrical cost assumes the currency is USD and there is no way to over-ride that (it may be because my primary AppleID is a US one - but I no longer live in the US).

**Comment by tnmendes** [comment]
Hey @Olghn,

- Recently another user also drew attention to this. In the next version, I will correct this error. Thank you for taking the time to report this issue :)

- Regarding your 2nd question you need to change the iPhone settings to do that go here:
Settings > General > Language & Region > Region > (Select your new country)
