### ISSUE TITLE
Docker API

### ISSUE THREAD

**Issue by Charlotte885** [tnmendes/watt#20]
have a web version only of all features to host on our own home. For privacy and offline use without relaying on internet.

**Comment by tnmendes** [comment]
I don't understand your question but there is only the iOS app

**Comment by Charlotte885** [comment]
in the future you are going to make a web version but that web version is
connected to iOS app and towards your server.

maybe you can create another same like this project?
https://github.com/jamesbarnett91/tplink-energy-monitor

so can be hosted in our own home.
