### ISSUE TITLE
Siri doesn’t work with Tapo P100

### ISSUE THREAD

**Issue by adrianrodsainz** [tnmendes/watt#21]
![ED09BAFB-2DAA-462F-A6EB-3F0791CD6599](https://user-images.githubusercontent.com/74065112/106942267-44760180-6724-11eb-87ae-981217f1781a.png)

I get this error message whenever I try to turn on/off any Tapo P100 smart plug. Does anyone know a solution?

**Comment by tnmendes** [comment]
Hey @adrianrodsainz 
Are you using the P100 but can you confirm the Hardware Version? (to check you need to use the Tapo App > select the Plug > Device Settings > Device Info > Hardware Version)

Can you check if you have the latest Firmware Version? 
For the Hardware 1.0.0 is 1.3.4
For the Hardware 1.20.0 is 1.4.3

Do you have more Tapo or Kasa Smart devices? If yes are they working?

**Comment by adrianrodsainz** [comment]
I have firmware v 1.2.9 with hardware 1.20.0, but for some reason it says the firmware is up to date

Might be a region lock or something
![image](https://user-images.githubusercontent.com/74065112/107036323-bea49580-67b9-11eb-90e3-4029f445ff98.jpeg)![image](https://user-images.githubusercontent.com/74065112/107036328-c106ef80-67b9-11eb-91a5-07ad59fe2edf.jpeg)

**Comment by tnmendes** [comment]
Hmmm it's really strange. There is another screen that you can use to update the firmware. When you open the Tapo app at the bottom you can click "Me" then "Firmware Update"

Can you also confirm that you have the latest version of the ios Tapo app?  (that is 2.2.38)


If any of the solution work can you open a new issue on the TP-Link forum
https://community.tp-link.com/en/smart-home/forum/614

**Comment by tnmendes** [comment]
Regarding this issue already exist on a thread about this

https://community.tp-link.com/en/smart-home/forum/topic/247704

_"For the Tapo  P100 V1.2,  firmware 1.4.3 has been suspended for a while but the new firmware with smart action will be released soon."_

**Comment by tnmendes** [comment]
@adrianrodsainz I think you can already update now your Tapo. This should solve the problem ;)

https://community.tp-link.com/en/smart-home/forum/topic/247704?replyId=567128

**Comment by adrianrodsainz** [comment]
It works perfectly, thank you!
