### ISSUE TITLE
Allow fractional cents in energy cost

### ISSUE THREAD

**Issue by bstrand** [tnmendes/watt#22]
In Settings -> Update Energy Cost, the field for entering the cost per kWh only allows whole cent values. 
Most power prices have fractional cents (e.g. 0.3325 USD per kWh)
It would be valuable to be able to enter a cost with more decimals of precision.

**Comment by tnmendes** [comment]
Hi @bstrand, 
Your suggestion is good but nevertheless, I have to keep the balance between usability of the app and more "nerdy" features. I think that this change will add more entropy to certain users.

Still thanks for being interested in contributing to improving the app.

**Comment by bstrand** [comment]
If someone is entering their electricity pricing into a smart home controller app, I feel like it's a safe assumption they've cleared the "nerdy" bar. ;) But I certainly understand wanting to keep it simple. 

Thanks for your consideration.

**Comment by tnmendes** [comment]
I had a lot of problems with that screen in the past. A lot of users don't know the energy cost so they just closed the app when asked. 

So I had to create a giant list of the price per kWh in the world to avoid having to compel users to write.
You can check here the list:
https://github.com/tnmendes/watt/blob/master/listWorldEnergyPrice
(and yes on my list I am using cents)

I think that I can add a toggle button to that screen to active cent values
