### ISSUE TITLE
No y axis scale on consumption bar charts

### ISSUE THREAD

**Issue by bstrand** [tnmendes/watt#23]
The historical usage bar chart in the Consumption screen has no scale on the Y axis.

This demonstrates trends, but without a scale to specify actual amount of power used, its utility is limited.

**Comment by tnmendes** [comment]
I'm already working on a redesign of the app that will solve this gap in the Y-axis.
Here is a sketch of what I'm thinking of doing:

![Chart Screen](https://user-images.githubusercontent.com/9822076/108780568-8a262d00-7560-11eb-98c2-ff5ed641273e.png)

Does it look good !?

**Comment by bstrand** [comment]
Looks great! Thanks for the engagement and your efforts.
