### ISSUE TITLE
Fail to tog(g)le switch: Tapo L510

### ISSUE THREAD

**Issue by gawdn** [tnmendes/watt#26]
Hi,

## Summary
When trying to turn on my Tapo L150 in the Watt app/via Shortcuts it fails to turn on with the message:

> Sorry...
Fail to togle switch

![image](https://user-images.githubusercontent.com/26182503/114851032-bb1a3400-9e24-11eb-8a0c-4d39209103eb.jpeg)

## Attempted steps
- It does work (can turn on the light/change brightness) in the native Tapo app.
- It was also working before and not certain what has changed. As I was figuring out the issue, I noticed that there was a firmware update in the Tapo app so I did that to see if it would fix it but it didn't.
- Logging out of the Watt app and logging back in (didn't work)

## Environment
- iOS 14.4.2 
- Watt 3.2.1
- Tapo Bulb Model L510 Series
- Tapo Bulb Firmware 1.1.9 Build 20210122 Rel. 56165
- Tapo Bulb Hardware Version 1.0.0

**Comment by tnmendes** [comment]
I will need to investigate this 
It is also failing with all my Tapo devices. I think TP-Link must have changed something on their server-side today because yesterday everything was working.

thank you for the warning

**Comment by honda7259** [comment]
I have the same issue today..., hope it can be solve.

**Comment by tnmendes** [comment]
It is not cool what Tapo did to Watt, it's not cool when Tapo decides to block the request of my app....Not cool  -_-

(Developers from Tapo team if you are reading this message if next time you have a problem with any of my requests please send a message and I will change it no need to block the app)


Anyway, Watt users you should already have a hotfix on the App Store v. 3.2.2, and your Tapo devices will work as normally 
@gawdn @honda7259

**Comment by gawdn** [comment]
thanks for the quick fix @tnmendes this is working now!

**Comment by honda7259** [comment]
Thank you so much!! you are the best!
________________________________
寄件者: Tiago Mendes ***@***.***>
寄件日期: 2021年4月16日 上午 02:12
收件者: tnmendes/watt ***@***.***>
副本: honda7259 ***@***.***>; Mention ***@***.***>
主旨: Re: [tnmendes/watt] Fail to tog(g)le switch: Tapo L510 (#26)


It is not cool what Tapo did to Watt, it's not cool when Tapo decides to block the request of my app....Not cool -_-

(Developers from Tapo team if you are reading this message if next time you have a problem with any of my requests please send a message and I will change it no need to block the app)

Anyway, Watt users you should already have a hotfix on the App Store v. 3.2.2, and your Tapo devices will work as normally
@gawdn<https://github.com/gawdn> @honda7259<https://github.com/honda7259>
