### ISSUE TITLE
LED night light 3 way Kasa switch 

### ISSUE THREAD

**Issue by hshempel** [tnmendes/watt#31]
LOVE your app. Can you make both LED night lights on both switches in a 3way turn off when you hit night mode? Right now I can only get one in the pair to turn off using your app.

**Comment by tnmendes** [comment]
Hey @hshempel, thank you for the Love :D
I'm just running a simple TP-Link command to turn the LED off so I don't have control of what TP-Link is doing.
So I won't be able to help you...sorry :-/

**Comment by hshempel** [comment]
Do you have any ideas for me on how to remedy? Your app can’t somehow recognize a 3 way switch from a 2-way? 

Thanks!’n

**Comment by tnmendes** [comment]
What device is are you using for the 3 ways? HS200, HS210, HS220?

**Comment by tnmendes** [comment]
Do you have the HS210 KIT? Is that?

Using the Kasa App can you see 2 different devices? And using my Watt you can see 2 different devices?
(I do not have any 3-way device so I don't know how the app is acting)

**Comment by Doblanko** [comment]
I have the same issue. The only 1 out of 2 3 way switches appear in the watt app. Therefore when you turn off the LED light it only turns off on one.

**Comment by tnmendes** [comment]
@Doblanko so the device that you have is "HS210 KIT"?

**Comment by Doblanko** [comment]
Yes

**Comment by tnmendes** [comment]
I was investigating and I don't think it's possible to turn off the led light of the other device. One of the devices is the "master" and the other is "slave". TP-link API is only showing one of them so only possible to control and to have access to just one of the devices.

**Comment by elitepuckster** [comment]
I also have the KS210 Kit.  What I like about their 3 way switches is they both don't have to be used on a 3 way circuit.  You can use 1 of the KS210s and a normal 3 way switch.  Then you can disable the white ring in the Watt app.  I have done it several times.  If you want to use both KS210s in the same 3way circuit, you can accomplish this by installing one of the KS210s, with the other being the normal 3 way switch.  Go into the Watt app and turn off the night light (white ring).  Once you do this, swap  the KS210 with the other one in the kit.  Go back into the Watt app again and turn it off.  Then you can finish the install by replacing the normal 3 way switch with other KS210 you had turned off earlier.  Then both of them will have the night light off.

**Comment by tnmendes** [comment]
@elitepuckster that's good to know, thanks for the tip. Maybe @Doblanko and @hshempel can also do the same

**Comment by Doblanko** [comment]
That is good information! Thank you!

**Comment by tnmendes** [comment]
I am closing this issue with solution from @elitepuckster
`I also have the KS210 Kit. What I like about their 3 way switches is they both don't have to be used on the same 3 way circuit. You can use 1 of the KS210s and a normal 3 way switch. Then you can disable the white ring in the Watt app. I have done it several times. If you want to use both KS210s in the same 3way circuit, you can accomplish this by installing one of the KS210s, with the other being the normal 3 way switch. Go into the Watt app and turn off the night light (white ring). Once you do this, swap the KS210 with the other one in the kit. Go back into the Watt app again and turn it off. Then you can finish the install by replacing the normal 3 way switch with other KS210 you had turned off earlier. Then both of them will have the night light off.`
