### ISSUE TITLE
Siri shortcuts stopped working

### ISSUE THREAD

**Issue by dan7769** [tnmendes/watt#34]
My Siri shortcuts have stopped working. She tells me "something's gone wrong." When I try to do it from the Shortcuts app, it says "There was a problem communicating with the app." Is this a known issue, or unique to me? Using an iPhone 12, iOS 14.6. Thanks!

**Comment by dan7769** [comment]
BTW, I tried deleting Watt and reinstalling, including having to re-enter all of my spaces (and confirming them in Shortcuts). For whatever reason, one space (Living room, if it matters) now works, but none of the others do. I also tried force-quitting Shortcuts (and Watt), with no effect.

**Comment by tnmendes** [comment]
Hey @dan7769 do you have more than one iPhone or iPad with the same Apple user? 

Are your devices Kasa Smart or are Tapo? 

Using the app can you turn on and off all devices from space? (click ▲,  then click "space", then slide to "Turn on")
You should see a message saying the result

**Comment by dan7769** [comment]
I have one iPhone and one iPad with the same Apple user.

My devices are Kasa.

In the Watt app, yes, I can turn those spaces on & off. In the Shortcuts app, no, I cannot.

Thanks!

**Comment by tnmendes** [comment]
I think that the error maybe be related to the same Apple User
That is related to this issue:
https://github.com/tnmendes/watt/issues/12


Did you create some shortcuts using the iPad? Or using the iPad the voice requested work?

**Comment by dan7769** [comment]
I did install Watt on the iPad, but I'm pretty sure I made all of the Shortcuts on the iPhone. I may have made them again on the iPad - I don't remember. I didn't experience any problems until iOS 14. If this is the issue, will deleting Watt on the iPad fix it?

**Comment by tnmendes** [comment]
So my suggestion to you is to open the apple app "Shortcuts" and delete all the shortcuts that are related to Watt.
Then add again using just the iPhone. (the shortcuts will be automatic copy to the iPad because of the Apple Cloud but the shortcuts related to Spaces will not work in the future in the iPad)

**Comment by dan7769** [comment]
Unfortunately, this did not work.

**Comment by tnmendes** [comment]
So now I'm out of ideas of what it could be ¯\_(ツ)_/¯

I will leave this issue open to see if anyone else complains about this
