### ISSUE TITLE
Add support for EP10

### ISSUE THREAD

**Issue by mlo1088** [tnmendes/watt#36]
Hi, I have 10+ Kasa devices but when I try to add, the "Choose Devices" screen says add up to 16 devices but only 7 of my devices show up as options.

**Comment by tnmendes** [comment]
You have the Smarter Power Strip HS300 right? I'm miscounting strips

**Comment by mlo1088** [comment]
Doh! I just realized all my new EP10 smart plugs are missing! That’s the common denominator

**Comment by mlo1088** [comment]
I do not have a power strip HS300. Just a bunch of smart plugs and smart light switches: HS103, HS110, HS220, EP10

**Comment by mlo1088** [comment]
HS300 is on my wish list though

**Comment by tnmendes** [comment]
I didn't know the EP10 was already on the market. I will try to add that device to the supported list.
Thanks

**Comment by mlo1088** [comment]
Same! Amazon prime day already had 4 pack used “like new”ones on sale for $18.

**Comment by mlo1088** [comment]
Yup all good now! Thank you for the quick fix!

**Comment by scottm1971** [comment]
I have an HS103 plug and I'm _considering_ the new EP10 model.  Will the app allow me to disable the LED for the EP10 like it does for the HS103?  Thanks!

**Comment by mlo1088** [comment]
@scottm1971 - i just tested on my ep10 and yes, the ep10 led turned off while still powering my device.

**Comment by scottm1971** [comment]
> @scottm1971 - i just tested on my ep10 and yes, the ep10 led turned off while still powering my device.

Awesome.  Thank you!
