### ISSUE TITLE
Space energy (kW) not updated

### ISSUE THREAD

**Issue by Tctan91** [tnmendes/watt#37]
In main page where multiple spaces are viewed; the kW info is not updated on each individual space. 

On the left top corner live consumption, the kW is accurately reflecting real time value.

When entering the space, the kW is accurately reflecting real time value.

**Comment by tnmendes** [comment]
Hey @Tctan91 

Can you take some print screens and share where are the issues?

**Comment by Tctan91** [comment]
Hi. First I would like to thanks for great apps. I like it a lot.

Here I share the screen record.


Sent from my iPhone

On 17 Jul 2021, at 2:26 AM, Tiago Mendes ***@***.***> wrote:

﻿

Hey @Tctan91<https://github.com/Tctan91>

Can you take some print screens and share where are the issues?

**Comment by tnmendes** [comment]
It's good to know you're liking the app :D

It seems that replying to the email with images doesn't work. 
Can you open the website and add the image here directly? Thanks

The URL link for the issue is:
[](https://github.com/tnmendes/watt/issues/37)

**Comment by Tctan91** [comment]
![9294927B-DE24-4424-85A0-9E64A39498B6](https://user-images.githubusercontent.com/87511024/126236773-93a71a64-a888-412b-b158-2ad8a03eb22d.png)

**Comment by tnmendes** [comment]
That is really strange, is this happing with other spaces? If this is not happing can you delete this space and create it again to check if this stops happing?
