### ISSUE TITLE
Support for KL125 Smart Bulbs

### ISSUE THREAD

**Issue by sbibauw** [tnmendes/watt#38]
Hi. Thanks for this great app! I was a bit disappointed that the KL125 smart bulbs (RGB colors) aren't supported. I suppose it's because they're kind of new?

Thanks anyway!

**Comment by tnmendes** [comment]
Yeah, it's a new light bulb and I haven't had a chance to investigate it yet.
In one next release, I will try to add KL125

**Comment by tnmendes** [comment]
its now supported with the versions 4.2
