### ISSUE TITLE
Can Not Delete Device

### ISSUE THREAD

**Issue by hdTechNutcrat** [tnmendes/watt#39]
The Watt app does not provide a way to remove/delete a device. 

I previously owned an HS103 that I no longer have access to and removed it from my Kasa account. The device name still appears in the Watt app even though newer device additions to the Kasa account devices, and changes to device names in Kasa, are successfully synced and reflected in the Watt app.

Pressing the HS103 device tile from the Watt app Space main screen results in a "Wait for the device loading" message for a few seconds (which can never complete since the physical device is gone) before returning control to the Watt app Space user interface without further processing. 

Please add a dot.dot button on the device tile or long-hold press event on the device tile that brings up a short context menu with a Remove Device option. 

It appears that the app currently tries to communicate with the device/Kasa account when the device tile is pressed, resulting in the "Wait for the device loading" message, then fails and continues at the Space main screen. A more comprehensive fix to the issue is that instead of failing, continue to the device detail screen but grey out / disable buttons that require communication like device on/off, put a header or footer message on that device detail screens similar to "Currently unable to access device", which would allow looking at past usage history (for a KP115 for instance), as well as include a similar menu option to Delete/Remove the device from the Watt app.

Currently, within the Space main screen in Watt app that contains the Kasa-deleted device, pressing Plus Sign to Choose Devices does not include the HS103 device that was deleted in Kasa, so therefore can not attempt to unselect it from the devices included in this space within the Watt app. (Watt app Space Plus Sign device list has 6 entries (reflecting the current Kasa account 6 devices), while the Watt app Space main screen has 7 entries including the Kasa-deleted HS103).

Thanks!

**Comment by tnmendes** [comment]
Hey @hdTechNutcrat  thank you for open the issue.
I will try to fix/improve this but in the meantime what you can do is delete Space and make new Space again

**Comment by hdTechNutcrat** [comment]
If I delete the space and recreate, will the electricity monitoring history going back months / year of my KP115 plugs be lost and restart building up history from when I recreate the Space, or is that info stored within the physical device, or stored in the Kasa account, and not stored in the Watt app? Thanks!

**Comment by tnmendes** [comment]
Yeah, the information is stored within the physical device, so you are not going to lose information by deleting the space :D
