### ISSUE TITLE
As this is a free app, where is the source?

### ISSUE THREAD

**Issue by ravn** [tnmendes/watt#4]
As this is a free app (which is fine) I was looking for source (as I need a system that will give an alarm if the HS-110 reports the power usage drops beneath a given threshold) but cannot locate any information on that.

Perhaps you would like to add a section providing instructions?

**Comment by tnmendes** [comment]
Hi @ravn, I currently do not have this functionality developed in the app, only when I progress to the development of a server will I be able to have this. 
I'm using github just for issues reports, the code I'm developing is not open source but on GitHub there are other projects that are open source it's easy to find.
