### ISSUE TITLE
Watt not showing Tapo devices

### ISSUE THREAD

**Issue by Mickeyg04** [tnmendes/watt#40]
Have both Kasa & Tapo apps installed on iOS. Watt picks up Kasa only. Tried logging in/out of current sessions. 
Have Tapa wifi cameras c100 & C200.

**Comment by tnmendes** [comment]
Hey @Mickeyg04 Watt is not supporting any type of camera. We are just supporting Plugs, bulbs, and switch from Kasa and Tapo.

**Comment by Mickeyg04** [comment]
Dam. Bought a couple of typo cameras thinking I could control all TP link
devices with one app when I saw yours.
