### ISSUE TITLE
Nothing happening on MacBook Pro 

### ISSUE THREAD

**Issue by whatisPLOTH** [tnmendes/watt#43]
I have downloaded the Watt app from the App Store - the window opens king for the sign in and password. 

I can enter text, though there is no button to "sign in" 
I have tried hitting enter, tab enter etc etc. 

Nothing seems to log in so the app does nothing. 

What am I missing>

**Comment by whatisPLOTH** [comment]
Using MacBook Pro with Big Sur 11.4

**Comment by tnmendes** [comment]
You don't have the login button at the bottom like this print screen? 

<img width="1154" alt="Screenshot 2021-10-03 at 18 16 29" src="https://user-images.githubusercontent.com/9822076/135762547-a1ff7764-3feb-4725-a927-0b5c89fbd06f.png">

**Comment by tnmendes** [comment]
Can you take one print screen?

**Comment by McCalle** [comment]
Sorry, found it...
