### ISSUE TITLE
Tapo L-900 Support

### ISSUE THREAD

**Issue by inepenthe** [tnmendes/watt#44]
Hello is it on your plans to intergrade Tapo L-900 -5 (RGB Light strip) on Watt Application?

(Hardware Version 1.0 - Firmware Version1.0.7 Build 210918 Rel. 152936)

**Comment by tnmendes** [comment]
Hey @inepenthe I am going to order one Tapo L900 and check/study if is easy to implement on Watt

**Comment by tnmendes** [comment]
Hey @inepenthe Tapo L900 is now supported in the new version of Watt 5.1.4
