### ISSUE TITLE
software won't update or reload from App Store

### ISSUE THREAD

**Issue by ElectroTech9** [tnmendes/watt#45]
I bought a copy of Watt for Smart Devices and got an update notice. When I clicked on the update icon, the software seemed to start downloading but immediately halted and now will not resume or load at all. I deleted the copy of the App on my Mac and Force Quit the App Store and then restarted it. Now I can't even get the Watt software at all. The App Store still thinks that it is going to download the Watt App.

**Comment by tnmendes** [comment]
It is possible that there is a problem with caching on MacOS, if you have time can you do some investigation on Google?
Example:
https://www.lifewire.com/can-i-fix-application-thats-not-starting-2260192
(There should be others websites with other solutions)
