### ISSUE TITLE
24 hour graph

### ISSUE THREAD

**Issue by timontrak** [tnmendes/watt#46]
How can I see a 24 hour consumption graph for a TP110 device?

**Comment by tnmendes** [comment]
Hey, @timontrak are you talking about the device Tapo P110 or Kasa HS110?

If you are talking about Kasa, the device does not store this type of information and if you're talking about brand Tapo it only keeps the Power 24H but I'm not showing that just the day chart

**Comment by timontrak** [comment]
yes definitely the Tapo P110. The listing on Amazon shows a 24 hour (hour by hour) graph, but I can't find this in the Tapo app

**Comment by timontrak** [comment]
This is the listing with the picture of the "last 24 hours" graph

**Comment by tnmendes** [comment]
On the Tapo app you need to click here to see the chart:
![IMG_3A7F1C5AE3FD-1](https://user-images.githubusercontent.com/9822076/141867410-9766c9a9-0571-4231-99b8-cd43d62d5eec.jpeg)

**Comment by timontrak** [comment]
Perfect - thank you!
