### ISSUE TITLE
Live Current Power

### ISSUE THREAD

**Issue by smithonlineg** [tnmendes/watt#51]
Hi,

I'm not seeing "Current Power" or "On Time" values from the KP200 outlets.  Seems to be working for the HS200 switches fine.  
Seems to be the same on the iPhone 13 (iOS 15.1.1)(WattApp 4.3.0) & iMac 2021 (Monterey 12.0.1)(WattApp v.4.3.1).
Am I missing something to make the info available for the KP200 outlets like it shows for the switches?

Thanks in advance!
greg

**Comment by tnmendes** [comment]
I will try to investigate, thanks for the report

**Comment by smithonlineg** [comment]
Thank you.  Let me know if you need anything else or I can help in any way.

**Comment by tnmendes** [comment]
Hey @smithonlineg  it's just to let you know that I've already developed the code that will solve the problem and if everything goes well by the end of the week I should be able to release new version

**Comment by tnmendes** [comment]
You can now download the new version 4.3.7 and the issue should already be solved
