### ISSUE TITLE
Allow user to disable on/off for plug

### ISSUE THREAD

**Issue by andrewglass3** [tnmendes/watt#53]
Hi

I have a HS110 whilst looking at the KP115 when they are back in stock. Id really love the ability to be able to use my plug as a simple energy monitor and have the ability to disable switching the plug on and off remotely or via the app. This is to avoid accidental power off of my home server or router.  I know I could get an intelligent PDU but thats a bit overkill for a home network.  With the massive cost increases in UK energy supplies at present, it would be great to see how much my old 4790k server running plex and other services is using up.

Thank you in advance for your consideration.
Andrew

**Comment by tnmendes** [comment]
Hey Andrew,
Just to be sure you want some kind of confirmation button on the Watt app when you pressed the button to turn on or off some of your devices?

**Comment by andrewglass3** [comment]
Good morning and Happy New Year :)

Thank you for getting back to me. Yes that would be a great idea or somewhere in settings for each device there could be an option to disable the on off feature of the plug?

**Comment by tnmendes** [comment]
In the last releases I've only been fixing bugs but I'll try to add this feature in the next release.

**Comment by tnmendes** [comment]
Hi guys, @andrewglass3 @bremen1874 @doctorbandaloop in version 4.5.0 I solved this problem. Check if this solution solves your problem :)

**Comment by bremen1874** [comment]
Just tried the updated version, and the new feature works well. A very worthwhile addition.
