### ISSUE TITLE
can't open the app (FIXED)

### ISSUE THREAD

**Issue by trexking** [tnmendes/watt#54]
Hi Tiago,

Thank you so much for creating this amazing app.  This app really help me to monitor my tp-link devices. I also really like the idea of chart and usage history.  

However, today I cannot open this app again on my iPhone (iOS v15.2).  I tried to reinstall it and it crashed after enter my login details.   
Is there any solution to fix this?  

Thanks!

**Comment by tnmendes** [comment]
I am currently working on a solution to that problem, I am also having that issue.

**Comment by tnmendes** [comment]
I have already fixed the bug!!! I'm just waiting for Apple's approval now that can take from 12 hours to 24 hours.

**Comment by trexking** [comment]
Thanks Tiago.  That's awesome news. 
Well done :)

**Comment by wjcroft** [comment]
Tiago, thanks for the quick fix. Also see same issue on my Mac Mini running Catalina. Attached macOS crash report traceback.

Regards, William

[watt-crash-Jan1.txt](https://github.com/tnmendes/watt/files/7797479/watt-crash-Jan1.txt)

**Comment by DerekGH47** [comment]
I am also having an issue with the App, it does not open. Tried reinstalling but still no success.
It would be good to know if there is something else I can try.

**Comment by Pilottech** [comment]
I am also having the same issue, unable to open the app on Catalina 10.15.7.  It has been working fine.  Uninstalled and reinstalled, no change.

**Comment by tnmendes** [comment]
Hey Watt Users sorry for the app iOS/MacOS is crashing like this.
I'm aware of the error and I've already made a bug fix for that but I am still waiting for Apple's approval/review. 
The status of the Watt app on the App Store is still the same waiting for review 😞
Usually, they are quick to review (24 hours) but probably with the New Year festivities they should be working slower.

**Comment by tnmendes** [comment]
***** IMPORTANT  *****

You can already update your apps to 4.3.3 iOS and MacOS where this ugly issue is fixed!!!

**Comment by DerekGH47** [comment]
Thank you very much
Much appreciated 

 
 
	

Thanks,
Best Regards

Derek Holton

Telephone 
Home: +44(0)1388 603773 - Mobile: +44(0)7485 431635
1 Clyde Terrace, Coundon, Bishop Auckland, Co Durham, DL14 8NJ

what3words address: ///mess.warm.salsa
https://w3w.co/mess.warm.salsa

 
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.

Sent from my iPad

On 2 Jan 2022, at 13:02, Tiago Mendes ***@***.***> wrote:

﻿
***** IMPORTANT *****

You can already update your apps to 4.3.3 iOS and MacOS where this ugly issue is fixed!!!

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Pilottech** [comment]
Thank you for the very quick response.  Both IOS and Mac versions are working just fine.
