### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by rgnet5** [tnmendes/watt#56]
Please add support for EP40 Outdoor switch, and also an option to save to iCloud or otherwise add the ability to share data/configuration between devices (iPad and iPhone). Thank you.

**Comment by tnmendes** [comment]
in the last few months, Kasa Smart has launched several new devices that I still don't support, I will try to change this situation. Thanks for letting me know 👍
Regarding your second suggestion, I want to do that, but to do that I'm going to have to do a big refactoring of the code I use today and the database, so it won't happen anytime soon :-/

**Comment by rgnet5** [comment]
Thank you!

**Comment by doctorbandaloop** [comment]
Would love a way to disable the on/off switch for more critical devices that I'm just using the energy monitoring features of the kasa plug for.

Also eagerly awaiting ability to export usage data!

Thanks for making such a nice alternative to the official app!

**Comment by tnmendes** [comment]
@rgnet5 In version 4.4.1 EP40 is now supported!!

@doctorbandaloop regarding your request I did not forget and I will in the next version launch this feature. There is already an open issue with the same request, here is the link:
[https://github.com/tnmendes/watt/issues/53](https://github.com/tnmendes/watt/issues/53)

**Comment by rgnet5** [comment]
Great news!  Thank you.

**Comment by doctorbandaloop** [comment]
Thanks for your work! Looking forward to it, I will keep an eye on the other thread.
