### ISSUE TITLE
Ks230 kit does not show up

### ISSUE THREAD

**Issue by Ryan11227** [tnmendes/watt#57]
Add support for ks230 kit including both switches (main and satellite). Currently they don’t show up in the watt app at all. 

Or is there a way to refresh the watt app to get ks230 to show up?

**Comment by tnmendes** [comment]
Hey @Ryan11227 I haven't had time to look at this new device from Kasa yet.
I will try to add support or that device. Thanks for letting me know 👍

**Comment by elitepuckster** [comment]
Yeah, I was here for the same thing.  If when looking at this you can figure out how to turn off the power indicator on the secondary switch, that would be awesome.  The normal KASA app lets you turn off the LED indicator, but that only affects the main switch, not the secondary.

**Comment by tnmendes** [comment]
@Ryan11227  and @elitepuckster In version 4.4.1 ks230 and KS220M are now supported!!

**Comment by Ryan11227** [comment]
Now that it’s added does it allow for control of the main and satellite switch? Particularly ability to control the satellite LED indicator
