### ISSUE TITLE
Kasa KP303 "Protected" LED Doesn't Turn Off

### ISSUE THREAD

**Issue by 10kingsam** [tnmendes/watt#59]
![KP303](https://user-images.githubusercontent.com/68732863/152803787-a21084c5-ca09-4faf-adc2-4afe9c0088c4.png)

When activating Night Mode, all LEDs turn off excluding the "Protected" LED (the one circled in the attached image).

Possibly linked to Issue#31 but that doesn't mention the KP303.

**Comment by tnmendes** [comment]
Hey @10kingsam  this is a hardware limitation that you can't turn off the protected led

**Comment by 10kingsam** [comment]
Hi @tnmendes 

I thought this might be the case but worth checking

Thank you anyway, awesome app!
