### ISSUE TITLE
Subscription 

### ISSUE THREAD

**Issue by upriis** [tnmendes/watt#6]
Hi,
Great app, looking forward to future developments. 
I’ve subscribed via my iPad but I cannot get my zones on the iPhone. When I try it goes through to the subscription page and it cannot restore purchase on the phone.

**Comment by tnmendes** [comment]
Hi Upriis,

Thank you for supporting this project :D
I'm sorry this is happening, can you confirm that you have the same iTunes user on your iPad and iPhone? (To do that you have to go Settings > iTunes & App Store > Apple ID)

**Comment by upriis** [comment]
Hi Tiago,

I can confirm it’s the same iTunes account on both devices

**Comment by upriis** [comment]
Further to my last, I’ve re-installed and played about and it’s working great. 

Thanks for the app! It’s exactly what the Kasa app should be.....
Looking forward to developments and seeing new features 

Cheers
Neil

**Comment by tnmendes** [comment]
Phew, what a relief!!! I'm glad it's already working xD
@upriis can you make this same comment as a review in App Store? Reviews help the app reaches more people, thank you!

**Comment by upriis** [comment]
Reviewed!
⭐️⭐️⭐️⭐️⭐️
