### ISSUE TITLE
Runtime Cumulative not working for Tapo P110?

### ISSUE THREAD

**Issue by bremen1874** [tnmendes/watt#60]
I've recently started using the app with some Tapo P110 smart sockets.

On the graphs, the consumption seems to work as expected, but the runtime isn't showing anything. Is this a limitation of the P110, me not understanding what it's supposed to show, or a bug?

![Watt app](https://user-images.githubusercontent.com/99551715/154485623-57f47ef8-4e8a-4664-b322-7437aeb8f664.jpg)

**Comment by tnmendes** [comment]
Hey @bremen1874, this happens because on Kasa Smart branded devices I can read the Runtime but with the Tapo brand, I couldn't yet find a way to read this data.
