### ISSUE TITLE
Kasa Smart Strip

### ISSUE THREAD

**Issue by lewypierson** [tnmendes/watt#61]
Not sure if the Kasa smart strip is a model that’s not supported, I can see the strip in the Watt app, even see the current consumption of each device that’s plugged into the strip and currently running. I just can’t make Siri Shortcuts for each outlet on the strip. It defaults to the entire strip itself. Very annoying going from controlling Individual Kasa plugs with Siri to buying a $50 strip and can’t control them independently with Siri

**Comment by tnmendes** [comment]
Hey, @lewypierson  there is a small issue with strip and Siri.
But there is a workaround on your iphone/iPad search for the app Shortcut, 
- click "+"
- click "Add Action"
- click "Apps"
- search for Watt
- click "Change to On/off your Kasa Smart Device"
- click State it can be On or Off
- Click Device and search for name of one plug from the strip

**Comment by tnmendes** [comment]
example:
![IMG_DAB7ED32F220-1](https://user-images.githubusercontent.com/9822076/160120981-82a56d70-a669-4544-898f-b1762523a479.jpeg)

**Comment by lewypierson** [comment]
Search for the shortcut and hit +? Is the plus within the app? Like do I open the app then hit plus? you mean watt? Or the actual Kasa app?  When I use the iPhone or iPad search for the app.. I dont see a plus option before I open the app

**Comment by lewypierson** [comment]
ahhhhhhhhh I see lol in the app Shortcuts.. I read that as the app shortcut, meaning for Kasa

**Comment by tnmendes** [comment]
Yeah the app shortcut from Apple...did it work for you?

**Comment by lewypierson** [comment]
It did thank you.. I now know a knew way to use short cuts.. i had never noticed the “apps” tab within shortcuts before.. Thanks!
