### ISSUE TITLE
Additional Features Requests

### ISSUE THREAD

**Issue by moharash** [tnmendes/watt#62]
Dear,

first i would like to say thanks for the great application, i bought a subscription for 1 year recently and was using the app recently. i have few useful suggestions for the app usage that would give it a lot of value.

1* Voltage Sensor:
i realized that the app reads the Voltage from the smart plug, but nothing else. one very important feature is turn off the plug if the voltage go under 140 or go above 260 to protect the equipment like my 220V refrigerator. showing charts for Voltage will be great to monitor if any fluctuation in voltage is happening throughout the day.

2* Daily Charts with hour or minutes sampling:
having such an option is very useful to some users and it could come to a cost, coz it needs more storage. make it optional and you will have myself as the first subscriber.

3* i have Sonoff sensors to some circuit breakers in my house, it would be great if you extend your support to Sonoff or other products than Tplink.

4* add a feature to delay the plug to power on after electricity On/Off to protect the equipment connected to the smart plug. as you may know, it is recommended to allow for 30 seconds at least after power cut to turn on again big equipment like refrigerators.

5* Add more currencies to the application so we can change it from GBP, i am currently in Lebanon for example... so appreciate if you can add LBP as a currency or USD at least so i can see the real cost which is in LBP or USD in my case.

i have a lot more, but i dont want to bombard you with all ideas

Please let me know if its acceptable and if these ideas could be part of the roadmap.

Appreciate all your works guys

Regards,
M Rashid

**Comment by tnmendes** [comment]
Hi @moharash, thank you for your suggestions and the subscription. 
I will try to answer each point

1* I just added this point to the roadmap:
"Monitor the voltage and if it is out of normal values send a warning or/and turn off the device"

2* In relation to the second point is already on the roadmap:
 "Record the energy consumption hour by hour"

3* I only work on this project in my spare time, so I can't split the time into adding more brands to the project :-/

4* In the next update I want to add a new feature that will be a toggle that you can activate on each device. Once activated to turn Off or On the device, you will have to slide to toggle. This will prevent you from accidentally turning the system on or off. 

5* Regarding the currencies I'm reading what you have defined in your iOS settings. When you login I try to look at your iOS settings currencies and region, and based on that I am setting how much kWh costs for your country. For example Lebanon I am assuming the cost of 116.725 Lebanese pound per kWH (This value is more than a year old, so it may be out of date).
You can check here my public list:
https://github.com/tnmendes/watt/blob/master/listWorldEnergyPrice

To check your iPhone region. Open the iPhone settings, click general, click Languague & Region

**Comment by moharash** [comment]
Thanks a lot for the reply,

kWH price in lebanon is now around 0.4$, adding USD will be a good option
