### ISSUE TITLE
Nothing in data log

### ISSUE THREAD

**Issue by IIBBYY** [tnmendes/watt#63]
All of a sudden the app is no longer entering anything into the app.

I am not seeing any numbers for usage or how much its costing me.

**Comment by tnmendes** [comment]
@IIBBYY What devices do you have? 
If the devices you have are Tapo and you have them outside your country it will not work.

Can you share some print screens?

**Comment by IIBBYY** [comment]
Turns out all I needed to do was reset the KASA smart plug. reset my router. Delete WATT and re-install and now its coming up with usage and cost.

**Comment by tnmendes** [comment]
A lot of steps but i am glad you have everything working again :D

**Comment by IIBBYY** [comment]
![image](https://user-images.githubusercontent.com/77249980/160243002-3a0596f9-7d2d-42fc-9a1c-e85216ed0fe9.png)

It's happening again

**Comment by tnmendes** [comment]
Can you tell me what device that you have?

**Comment by IIBBYY** [comment]
![image](https://user-images.githubusercontent.com/77249980/160277043-386c7473-2260-4106-85ba-f70f3abaffe0.png) 

X2 plugs

**Comment by tnmendes** [comment]
Do you just have 2 KP105? You don't have any bulbs/lamps? The Kasa KP105 does not have the ability to read energy, so you can just see the runtime (how many hours it was on the plugs)
So would say that the chart are correct

**Comment by IIBBYY** [comment]
What sockets would give me real time energy readings? I had the HS100 first but that doesn't work anymore and is discontinued.

Thanks

**Comment by tnmendes** [comment]
If you are interested in buying more plugs, take a look at these: 
Plugs with energy monitor you have Kasa HS110, HS300, KP115, KP125, and Tapo P110
(if you are US I recommend you the KP125 that supports HomeKit from apple)

I'm glad to have helped :D
