### ISSUE TITLE
support for kasa smart bulb KL135

### ISSUE THREAD

**Issue by 592turtle** [tnmendes/watt#65]
can you include support for the Kasa smart bulb KL135 I have two of these but it's not showing up when I sign in to the watt app on ios thanks.

**Comment by tnmendes** [comment]
Do you know the Color Temperature of KL135? Is it 2500K-9000K?

**Comment by 592turtle** [comment]
Yes that’s correct 


Sent from Yahoo Mail for iPhone


On Wednesday, August 10, 2022, 6:11 PM, Tiago Mendes ***@***.***> wrote:




Do you know the Color Temperature of KL135? Is it 2500K-9000K?

**Comment by tnmendes** [comment]
The bulb KL135 is now supported with the new version 4.5.4, when you have time can you test and check if everything is working well with the bulb (including changing color, and color temperature)?

**Comment by 592turtle** [comment]
yes I just updated and tested everything and it works this is my first time using the watt app one suggestion to make it a bit easy when it comes to setting the color temperature I don't know if there is an option to type in the color temperature manually cause I realize when using the temp wheel its very sensitive and also can WHITE be added to the list of colors when using Siri because when you use Siri to change the color lets say you need white you will have to go back into the Kasa app to change it from the color 

DWAYLON ROCKCLIFFETELE# 669-3676 

    On Thursday, August 11, 2022 at 04:47:48 AM GMT-4, Tiago Mendes ***@***.***> wrote:  
 
 


The bulb KL135 is now supported with the new version 4.5.4, when you have time can you test and check if everything is working well with the bulb (including changing color, and color temperature)?

**Comment by 592turtle** [comment]
it's so much better than using IFTT APP to control the lights 

DWAYLON ROCKCLIFFETELE# 669-3676 

    On Thursday, August 11, 2022 at 04:47:48 AM GMT-4, Tiago Mendes ***@***.***> wrote:  
 
 


The bulb KL135 is now supported with the new version 4.5.4, when you have time can you test and check if everything is working well with the bulb (including changing color, and color temperature)?

**Comment by tnmendes** [comment]
Thanks for the suggestion, I just added these two new entries to the Roadmap:

- Add new command to Siri so we can select Color Temperature from Bulb
- When you are on a Bulb information screen, add shortcuts for common colors and temperatures.
