### ISSUE TITLE
Login problem 

### ISSUE THREAD

**Issue by bobbaron3** [tnmendes/watt#66]
![ED613F30-1477-4E24-AEC9-1635098AFA6E](https://user-images.githubusercontent.com/54826581/172177613-ce7fc592-1a78-4608-ba74-23f664abf96f.png)

**Comment by tnmendes** [comment]
Hey @bobbaron3, thanks for reporting this problem.
I recently noticed that one of the latest updates to the Tapo app was that they added a Two-Step Verification, maybe is related to this.
I can't replicate with my email account right now, so I'm going to ask a few questions.
Is this your first time trying to log in to the Watt app?
Are your devices all Tapo brand? Or are they from the Kasa Smart brand?
When you enter the Tapo or Kasa Smart app, is it asked for Two-Step Verification?
What country are you in? United States?

**Comment by bobbaron3** [comment]
Hello Tiago,

 My devices are all Kasa/TP-Link. There is no two step authentication setup. Yes I am in the United States.

Thank You,
Bob

________________________________

**Comment by bobbaron3** [comment]
Hi Tiago,

 I just happened to notice I got notifications from Kasa app for unauthorized access and realized it had 2-step authentication on. I disabled it and can now login, but I would prefer to have it enabled but see no way to within the Watt app. Please advise.

Thank You,
Bob

________________________________

**Comment by tnmendes** [comment]
In my email account, there is still no possibility to activate two-step.
I think that TP-Link must have chosen a user group and activated that feature.
I even turned on a VPN for the USA but still I keep getting a message that it is still not possible to activate the two-step.

As soon as I find out how I can send the two-step code to the TP-Link servers, you will be able to activate the two-step again, but in the meantime you have to keep it deactivated.

Sorry for the inconvenience, but this is a third-party app and TP-Link makes changes without notifying any developer.
