### ISSUE TITLE
EP25 Mini Smart Plugs

### ISSUE THREAD

**Issue by stanishjohnd** [tnmendes/watt#69]
EP25 Mini smart plugs (https://www.kasasmart.com/us/products/smart-plugs/kasa-smart-plug-slim-energy-monitoring-ep25) are not recognized and do not appear in the available devices.

Please add support for these devices.

**Comment by tnmendes** [comment]
Hi, @stanishjohnd thanks for the suggestion I will try to add it in the next release!!

**Comment by tnmendes** [comment]
Is now available in version 4.5.3 of Watt, @stanishjohnd can you test and tell me if is working well for your EP25 plug?

**Comment by stanishjohnd** [comment]
EP25 plugs can be viewed when i added new devices to a room.

Thanks
________________________________
