### ISSUE TITLE
Watt causing my plugs to randomly restart 

### ISSUE THREAD

**Issue by kennc05** [tnmendes/watt#70]
Hello

I’ve noticed that when using Tapo and watt at the same time it causes my plugs to restart quickly. I’m not sure why this is? 

How can I look into this? My email is kenkyle236@icloud.com

thank you

**Comment by tnmendes** [comment]
Hey @kennc05 what do you mean by restart? What Tapo model do you have?
When you use the official Tapo app is not happing? If you turn off the wireless from your iPhone and just use the mobile internet with Tapo app is that happing also?

In Watt app I'm just using TP-link could servers so all my orders go to the TP-Link servers and then it is the TP-Link servers that transmit the orders to plugs and bulb.

**Comment by kennc05** [comment]
Hey @tnmendes sorry for the late reply back to you - I think I did some changes to my set up and it was actually wifi issues causing them to turn off and on again. I haven’t had any problems since but if there are I’ll come back here!

Thanks so much and take care
