### ISSUE TITLE
P115

### ISSUE THREAD

**Issue by xanderificnl** [tnmendes/watt#71]
Hi.

Any chance you can support the P115? 

I'm hoping its api is comparable (if not exsctly the same) as the P110. I can help test of you like!

Thanks, 
Friendly regards,

- Xander ;)

**Comment by tnmendes** [comment]
Hey @xanderificnl I just made a new update, in theory, is done, could you download version 4.5.4 and see if everything is working well with P115?

**Comment by xanderificnl** [comment]
Hi. I've installed the update, and the P115 is recognized. Thanks, that was quick! :)

Can you confirm that much like the P110, the P115 also keeps track of daily consumption? In the Tapo app, I can see daily consumption. in Watt, I'm getting an information message the P110 is the only Tapo that supports it. 

I've only had the device since yesterday, so I'm wondering if Watt already shows daily consumption for the P115, or not.

**Comment by tnmendes** [comment]
Great to hear that P115 is working well with the Watt app :D 
That is just a static message that I forgot to update, but everything that you have with P110 you should also get with P115.
