### ISSUE TITLE
device Consumption Enhancement request 

### ISSUE THREAD

**Issue by Charlotte885** [tnmendes/watt#74]
See the device Consumption even when the device is offline (is to know how much is energy is used when it was online), 
currently offline device will say Device unreachable and can’t go further to see the chart.

**Comment by tnmendes** [comment]
I'm always fetching data from Tp-Link servers when the device is offline the fetching will fail and I don't have enough information to show. That's why I show this message "Device unreachable".

**Comment by Charlotte885** [comment]
the energy consumption over the past few month store in your server right?
maybe can view the device energy consumption even when it in offline.

**Comment by Charlotte885** [comment]
Maybe can say device unreachable and show past energy consumption.

**Comment by tnmendes** [comment]
@Charlotte885  no, I don't store anything on the watt app (i don't have any server), what Watt do is always that the app is open the I'll get everything from the TP-link Servers, and the TP-Link servers communicate directly with the smart plugs to obtain historical consumption data.
So who is saving your data, in reality, is your plug.
