### ISSUE TITLE
Some P115 devices show up as "Device Tapo"

### ISSUE THREAD

**Issue by robpac** [tnmendes/watt#75]
Some devices have a name in the Tapo App but show up as "Device Tapo" in Watti.
It is not related to certain characters (like Umlaute) or spaces or pluses inbeetween the name.

**Comment by tnmendes** [comment]
Hi, @robpac thank you another user also reported this problem. I'm going to close this issue because there is already another thread already open.

Here is the other issue:
https://github.com/tnmendes/watt/issues/73
