### ISSUE TITLE
Tapo P110 and Android

### ISSUE THREAD

**Issue by netregha** [tnmendes/watt#76]
Hello,

I have some Tapo P110 smart plugs, and I am looking for a utility that I can use to reset the statistics easily rather than having to reset the whole device each time I move it to a different appliance.  I appreciate that your application is for IOS. I do have some code (not written by myself) that supposed to work with TAPO devices but the one command I want doesnt appear to work. Would you be willing to share the commands that are accepted by the TAPO devices.
thank you in advance
Darren

**Comment by tnmendes** [comment]
Hey Darren, I'm sorry but at the moment I can only reset Kasa Smart devices, I've already tried to investigate and try to find the Tapo reset but I still couldn't  :(
