### ISSUE TITLE
Export data to CSV

### ISSUE THREAD

**Issue by mydigitalbubble** [tnmendes/watt#79]
### Discussed in https://github.com/tnmendes/watt/discussions/78

<div type='discussions-op-text'>

<sup>Originally posted by **mydigitalbubble** September 23, 2022</sup>
I see there is reference to exporting the consumption history to CSV or Excel. Can someone guide me on how this is done? I cant see the option in the IOS app - or is it still a pending feature enhancement?

thanks</div>

**Comment by tnmendes** [comment]
Hey mydigitalbubble,

At the moment it is not yet possible to export, it is in the Roadmap (planned to develop in the future)
