### ISSUE TITLE
Device Unreachable

### ISSUE THREAD

**Issue by redonebe** [tnmendes/watt#81]
After the firmware upgrade of the Tapo P110 to 1.1.2 Build 220930 Rel. 144500 the plug is giving Device unreachable while in the Tapo app everything is working normally.

**Comment by Gilbertonl** [comment]
Same here. After firmware update (Automaticly pushed) the orginial app was also not working correctly. Needed to update the TapoApp as well. I think output is changed (JSON?)

**Comment by zepplmetz** [comment]
same here

**Comment by Gilbertonl** [comment]
I don't think you should blame the creator of the WATT APP. TPlink has changed something in the new firmware. The response is now changed. Let's hope he can fix it soon because i really like his app. :)

**Comment by Sandyleonard** [comment]
Same.

**Comment by tnmendes** [comment]
Hey guys, lately Tapo has been making big changes to their API. Normally I only discover changes after they have already happened. Is what I call Cat and mouse and with my constant pursuit.
I now need to investigate what they've changed and change my project in case a user is using the new firmware or using a new system.

@zepplmetz You don't need to pay a subscription to use Watt, you only need a subscription if you want to organize your devices by spaces/rooms. Each space can have 16 devices.

**Comment by kennc05** [comment]
My Tapo plugs recently had 2 firmware updates and it has certainly broken something in the Watt app - will subscribe to this thread to stay updated :)

**Comment by tnmendes** [comment]
With the new Tapo P110 firmware update, they change the method of getting energy consumption statistics.
This is the new method 

POST https://euw1-app-server.iot.i.tplinknbu.com/v1/things/.../usage
`{
  "method": "get_energy_data",
  "params": {
    "end_timestamp": 1667260800,
    "interval": 43200,
    "start_timestamp": 1640995200
  }
}`
Response:
`{
    "energy_data": {
        "local_time": "2022-10-22 20:17:12",
        "data": [
            32148,
            36482,
            28707,
            14642,
            16811,
            9126,
            12986,
            7617,
            13833,
            14733,
            0,
            0
        ],
        "start_timestamp": 1640995200,
        "end_timestamp": 1667260800,
        "interval": 43200
    }
}`


Let's see if I can find more changes to the API that are responsible for the "Device Unreachable" on Watt.

**Comment by Ildanach** [comment]
Similar issues. Two plugs updated firmware and now won't work in Watt. Got a new plug today and can't add it to Watt. Can see it in the list to add but can't select it. Hopefully all the changes to the API can be tracked down and the app updated soon.

**Comment by tnmendes** [comment]
I have good news guys, I already made a Hotfix to get Tapo P110 working again with the new firmware.
Right now the only thing that won't be working will be generating charts with annual data, the last 30 days will work.

I've already submitted the app for Apple review and now it should take between 24 hours to 48 hours to be available on the App Store

**Comment by tnmendes** [comment]
🔔🔔🔔 The iOS app Watt with the hotfix is now available on the App store (version 4.5.5)!!!!
The macOS version is currently under review so it should be available in a few hours.

**Comment by gfab-io** [comment]
Tapo P115, even after the latest update, is still unreachable (the plug works regularly on the Tapo app)

**Comment by redonebe** [comment]
The plug is reachable and the current power is there but the "Today Energy" stays 0 and there is no data in the chart display. Both the app and macOS give the same result.

**Comment by tnmendes** [comment]
@gfab-io I still haven't made the correction for the P115 just for P110. I have yet to confirm and investigate whether the same solution will work for the P115.

@redonebe Today Energy is not showing because of my gap, in the next version this will be resolved.
Regarding the problem in the graph, it shouldn't be happening anymore :-/ 
Could you help me to investigate, could you open the Tapo app and then click on a P110 device and then click on gear in the top right corner > Device Info > and confirm that the Time Zone is the same as the one on your phone?

**Comment by redonebe** [comment]
The timezone in the Tapo app: Europe/Brussels
In the phone settings: Brussels

**Comment by tnmendes** [comment]
There was a problem with the timezone, I already solved the problem using UTC in these requests.
Download the latest version 4.5.7 (when downloading pay attention to the version, because I sent 2 versions in the last 24 hours)

**Comment by Mutzki13** [comment]
The last updates brought back power consumption for each device (P110) separately, the live consumption, todays usage and cumulative consumtion is locked on 0 - that is within the iOS and the macOS app.

**Comment by tnmendes** [comment]
Hey, guys, I have a new updated app can you test the new Watt app version 4.5.8, and check if the issues are resolved?

**Comment by redonebe** [comment]
Everything seems working now. Thanks.

**Comment by Mutzki13** [comment]
👍
