### ISSUE TITLE
These don’t do what I bought them for. 

### ISSUE THREAD

**Issue by Sandyleonard** [tnmendes/watt#83]
I bought 8 p110’s about 6 weeks ago to data log electrical heating usage over a whole winter. Some had an issue, some worked okay. I cancelled my auto subscription which is due next September.  I have now lost all my data logged to date. Why are these sold as energy logging if you can’t data log in Tp links app? If TP link change something via an update surely they need to make sure the energy monitoring remains seamless via the supporting app (Watt). As it stands these are a total waste of money. Am I missing something here, can you monitor energy in Tp links own app?

**Comment by tnmendes** [comment]
Hey,

Both in the Watt app and in the Tapo app you can see the graphs, in the Watt app, it is more intuitive.
To see the graphics in the Tapo app you have to click here:

![IMG_461126B80B40-1](https://user-images.githubusercontent.com/9822076/197869862-3c8932e9-0273-4c60-80ab-2c643bd84adc.jpeg)

(If your interface is different try to update the app and then also update the firmware for each P110)

**Comment by Sandyleonard** [comment]
Thanks. I didn’t realise that part you circled is on the Tapo app. Any idea why my data has vanished on all my plugs in the Watt app?

**Comment by tnmendes** [comment]
Not really, I did not lose any data on my Tapo plugs but in the last few weeks there have been several updates
