### ISSUE TITLE
Stats are gone

### ISSUE THREAD

**Issue by Meribees** [tnmendes/watt#84]
Besides having my P110 renamed on Watt to “Device Tapo” it lost the data that it had for the last 20 days or so. In Tapo the data is there. But in Watt it shows nothing for these devices.

**Comment by tnmendes** [comment]
Please update to the latest version 4.5.7 (when downloading pay attention to the version, because I sent 2 versions in the last 24 hours)

**Comment by Meribees** [comment]
The devices now show the corrects stats. However the chart with all devices isn’t updating.  It says I consumed 244wh when each device consumed individually a bit over 3Kwh on the same period and I have two P110 on the same space. 

I’m currently on v4.5.7

**Comment by tnmendes** [comment]
Hey @Meribees  can you test the new Watt app version 4.5.8, and check if the issues are resolved?
