### ISSUE TITLE
kasa & tplink accounts not available at once?

### ISSUE THREAD

**Issue by ROBERCHR** [tnmendes/watt#85]
I read this blog post[blog](https://www.watt-app.com/blog-kasa-smart-and-tapo.html)  and assumed that i could control my tapo and tp-link devices from one account instead of via the kasa and tapo apps like i do today. However, it seems i have to log out of one and into the other in order to do it (i.e I cant see them both at the same time?

**Comment by tnmendes** [comment]
Hey @ROBERCHR you need to use the same email for Kasa and Tapo. You probably have 2 different accounts.
