### ISSUE TITLE
Overall usage and totals not working

### ISSUE THREAD

**Issue by Colinalbright** [tnmendes/watt#87]
Since last week update cumulative total now not working P110 Uk

**Comment by tnmendes** [comment]
Hey @Colinalbright can you test the new Watt app version 4.5.8, and check if the issues are resolved?

**Comment by Colinalbright** [comment]
Hi Tiago Its started showing something, but not the correct readings.. I downloaded and update the app yesterday at 16:00 UK time..., and it has been running overnight..   Colin Albright   IT Support Engineerm:  +44 7799 ***@***.***  From: Tiago MendesSent: 02 November 2022 18:10To: tnmendes/wattCc: Colinalbright; MentionSubject: Re: [tnmendes/watt] Overall usage and totals not working (Issue #87) Hey @Colinalbright can you test the new Watt app version 4.5.8, and check if the issues are resolved?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Colinalbright** [comment]
Still nothing working... Could you roll the app back to the one that was working..?

**Comment by Colinalbright** [comment]
Today’s update seems to have fixed it. All working again now 👍🏻

**Comment by tnmendes** [comment]
Hey, that is awesome, @Colinalbright was fixed with version 4.5.9?

**Comment by Colinalbright** [comment]
Yeah, 4.5.9 did it 👍🏻
