### ISSUE TITLE
Reset history.

### ISSUE THREAD

**Issue by LeeH22** [tnmendes/watt#90]
My data is somehow corrupt, how can I fix this? ![image](https://user-images.githubusercontent.com/40705861/204111319-a19f41eb-ae91-41a1-8663-2c92f313403c.jpeg)

**Comment by tnmendes** [comment]
Hey @LeeH22 you have to find which device has the wrong values and after finding it, just click on configuration btn at the top and then reset.

![91487](https://user-images.githubusercontent.com/9822076/204130949-2174d8af-14a5-4346-84db-fdc13e968986.jpg)

![36557](https://user-images.githubusercontent.com/9822076/204130955-453e2d3f-0a5c-46da-8168-6e39569ba791.jpg)

**Comment by LeeH22** [comment]
Many Thanks.
