### ISSUE TITLE
Frozen/non-updated Dashboard

### ISSUE THREAD

**Issue by awastl** [tnmendes/watt#93]
Hi,

I really like your App. Especially the different forcast values for yearly costs based on measurements of the different intervals. But having now increased to a total number of 13 Tapo energy monitoring plugs, my Dashboard is not updating any more. Maybe it was the case earlier, but I would say no it wasn’t. The dashboard shows consumption figures on the tiles which are of some point in time in the past. Sometimes a point in time many hours away. The overall consumption on the left upper corner seems correct and is dynamically refreshed. When I click on a singe tile, the then displayed „Current Power“ value shows the correct one. Closing the detail page to go back to the Dashboard, the old wrong value is still displayed. :-( The actually very nice dashboard is currently just kind of useless… :-(

I would really hope that you know about this already to look forward for an update… My devices are iOS and PadOS 16 powered. Thank you very much.

Kind regards,
Andy

**Comment by tnmendes** [comment]
Hey Andy, thank you for liking my app :D 
I will need your help to help better understand the error. So you only have Tapo devices, which models do you have? Is the  P110?
What timezone are the devices in? This question is important because in the previous firmware version I was having problems with this.
Do your devices have the latest firmware version? The latest version is 1.1.6 or is it the previous one?
Can you also share a print screen where this happens?

**Comment by awastl** [comment]
Good Morning Tiago,thank you for the quick reply from you side. :-)I was going to prepare the information for you and found the App working at the moment… Which is of course nice, but I doubt this will continue as I experienced the malfunction a couple of times before I contacted you. But I also did an iOS Update with restart of the phone and pad this morning.  Being a developer by myself, I know that there are always different circumstances and potentially crazy dependencies which we need to identify. So let me give you as much details as I can do now and deliver the screenshots which the next occuring malfunction….I run the App in Timezone CET.I have 13 P110 (all SW 1.1.6) and one KP105The K105 is disconnected from power since some days now. Up to now, I was not able to remove it from the dashboard as the ‚Choose Device’ screen somehow don‘t processed its deselection. Maybe the same reason for the lacking update of the dashboard? Now it worked and the K105 is gone. This is actually a change of my environment now which may change everything… Let‘s see.What I also experienced in the past non-refresh situation was: The removal of the power button (Safe Toggle) was not recognized from the dashboard. It was still shown. Unfortunately I never tried the switch from the dashboard to see if it would have worked still…That‘s it for the moment. Will come back with an update as soon as the problems reoccur.Kind RegardsAndyP.S. Please also count me in for those who like to switch off (get rid of) the haptic feedback when doing clicks on the icons. ;-)P.S. Diese Nachricht wurde von einem PAD geschickt.         (Bitte evtl. enthaltene Tippfehler überlesen.)Am 03.12.2022 um 01:16 schrieb Tiago Mendes ***@***.***>:﻿
Hey Andy, thank you for liking my app :D
I will need your help to help better understand the error. So you only have Tapo devices, which models do you have? Is the  P110?
What timezone are the devices in? This question is important because in the previous firmware version I was having problems with this.
Do your devices have the latest firmware version? The latest version is 1.1.6 or is it the previous one?
Can you also share a print screen where this happens?

**Comment by awastl** [comment]
Hi Tiago,
a short update. The refresh works so far for the P110. But: The KP105 is reconnected to power and renamed in the Kasa App. It shows up in the dashboard but with its old name. Klicking on the tile presents the new name. I can also not remove the tile as the Choose Devices does not show the KP105 at all… So there is some weired malfunction in the dashboard still.

**Comment by awastl** [comment]
Hi Tiago,a short update. The refresh works so far for the P110. But: The KP105 is reconnected to power and renamed in the Kasa App. It shows up in the dashboard but with its old name. Klicking on the tile presents the details with the new name. I can also not remove the tile as the Choose Devices does not show the KP105 at all… So there is some weired malfunction in the dashboard still.Kind Regards,AndyP.S. Diese Nachricht wurde von einem PAD geschickt.         (Bitte evtl. enthaltene Tippfehler überlesen.)Am 03.12.2022 um 01:16 schrieb Tiago Mendes ***@***.***>:﻿
Hey Andy, thank you for liking my app :D
I will need your help to help better understand the error. So you only have Tapo devices, which models do you have? Is the  P110?
What timezone are the devices in? This question is important because in the previous firmware version I was having problems with this.
Do your devices have the latest firmware version? The latest version is 1.1.6 or is it the previous one?
Can you also share a print screen where this happens?

**Comment by tnmendes** [comment]
Hey Andy,

Regarding the KP105 with the old name, probably when you removed from you TP-link account I kept it in phone Watt database. To solve this the easiest solution is to delete the app and install it again so you will have a new database.

The mini-chart behaves differently depending on whether you only have Tapo devices or you have Tapo and Kasa.

Your time zone is CET, the App is using UTC requests for the graph so it's only one hour different from CET. If happen anything is just after 23:00h.

When you have a device that is further away from the router (so slow communication), each refresh that happens every 10 seconds can take much longer.

Thank you for your feedback regarding haptic feedback.

**Comment by awastl** [comment]
Hi Tiago,

thank you for the detailed explanation. The App still works well. I really feel a bit uncomfortable that I raised the main issue of this thread…

Regarding the wrong title for my Kasa device: I actually never removed the device from the Kasa App. I just deplugged it for some days. This made it just unreachable. When I then put it back into an outlet I also changed its name in the Kasa App. And that changed name is what is correctly displayed when I open the details page of the the „wrongly“ named tile. So there is actually not a redundant tile in my list. Just the Dashboard does not shot the current name.

Your suggestion to delete everything and restore is probably a helping workaround solution, but it is just slightly cumbersome to do… I would need to activate the save toggle on for all the 13 devices one by one again. ;-) As I most likely will have name changes in the future again - this plug is a kind of test gadget - I am not keen to do… You got me, I am a bit lazy here… ;-)

So I still hope/assume that at one point in time you stumble over the missing update line or the existing update line in the wrong branch or order of your code… ;-)

But I am also locking forward for your planned export feature of the captured data. Hopefully not just 30 days but a full rolling year with all detail level… Or, what about feeding an MQTT Broker? Might be not than big different compared to an EXCEL export as it is more or less just sending JSON messages to REST endpoint.

Kind regards 
Andy

**Comment by tnmendes** [comment]
I'm working on a big update, and in this update, I'm going to completely change the methods I use to get devices and how I deal with them.
After finishing this update it will be easier to choose to export the data.

I will close this issue for now.
If necessary, we can open it again.

**Comment by awastl** [comment]
Sorry for not replying earlier. Thank you very much. This sounds very interesting. I will stay tuned. For the moment, the dashboard updates workes better and even the wrong name in my dashboard somehow corrected itself. Looking forward for your export/MMQT options.

Merry Christmas and a Happy New Year.
