### ISSUE TITLE
KP400 does not turn off

### ISSUE THREAD

**Issue by drumlinemus** [tnmendes/watt#95]
I have two KP400 for outdoor lights. One of them works and has both outlets used. The second only has one outlet used. Whenever I try to turn it off through the Watt app, it does not turn off the device. When I go into the specific outlet, I can turn it off. The device turns off in the kasa app.

**Comment by tnmendes** [comment]
I @drumlinemus  can you do a screen recorder video of what's going on? first, maybe do it with the device that is working and then with the other one that is not working.

In case you never did this is how to do a screen recorder video:
https://support.apple.com/en-us/HT207935

Thank you
