### ISSUE TITLE
Devices not recording any data into Watt App but it does in KASA and HOME EP-25's

### ISSUE THREAD

**Issue by Ezzassin** [tnmendes/watt#96]
Hello, I want to preface with I'm a noob at this. I have used your app for a few months and just turned into a little marshmallow. Any who, I have 4-EP 25's that used to work until a couple days ago.  My devices are showing up in the Kasa app and HOME for IOS as ACTIVE. However when I add the devices in the Watt  app they are not showing any energy consumption and says my devices are unreachable. I downloaded all the apps again and still showing zero. Any help with this matter would be appreciated! Thanks!

**Comment by tnmendes** [comment]
Hey, thank you for the marshmallow, let me see if I can help.
If you disable the wireless on your iPhone and only use only the Cell phone internet will your devices work on the Kasa app?

**Comment by Ezzassin** [comment]
No, when I turned off wifi and just used the cell phone with cellular they were unavailable in the Kasa and WATT app...

**Comment by tnmendes** [comment]
That means you have something blocking the plugs from connecting with the internet (TP-Link servers).
Check if there is something blocking in the Kasa app or if your home Router is blocking

**Comment by Ezzassin** [comment]
Reset everything, unplugged plugs, router, modem and re-set up...and we are up and running!!!! Thank you so much for your prompt response!

**Comment by tnmendes** [comment]
Awesome!!!! :D
