### ISSUE TITLE
Tapo P110 - Siri Get Device

### ISSUE THREAD

**Issue by AndreasSkarpelos** [tnmendes/watt#98]
Hi. I recently came across this app and started using it. 

I wanted to mention an issue I have with one of my smart devices.

By running the Get Device shortcut I can see the status for all KL110 devices but it fails with Tapo P110.

[Error](https://we.tl/t-wEFHywEAp7)

**Comment by tnmendes** [comment]
Hey Andreas,

Thanks for the bug report, I am now finishing Watt version 5.0 in which I refactored the entire networking system.
In this new version, this error will be resolved, even so, we will leave this issue open so that after the launch you can confirm that it solved the problem.

**Comment by AndreasSkarpelos** [comment]
Great news! Hope everything is  moving according to plan. Is there any ETA on the new version? 

Thanks for getting in touch so soon.

**Comment by tnmendes** [comment]
My goal is for it to be released within the next two weeks!!

**Comment by AndreasSkarpelos** [comment]
good luck all the best!

**Comment by tnmendes** [comment]
@AndreasSkarpelos Watt 5.0 is out can you test and check if the get device is working for you!?

**Comment by AndreasSkarpelos** [comment]
New version solved the problem! Works 100% now. Thanks!

**Comment by tnmendes** [comment]
Awesome!!!
